/**
 *  2_DML.sql
 *  Creación y carga de información a tablas generales para la aplicación de Visado Poderes.
 *  Esquema: VISPOD 
 *  Fecha: 02/01/2013
 *  Versión: 1 
 */

-- TIIVS_ESTUDIO --
INSERT INTO VISPOD.TIIVS_ESTUDIO (COD_ESTUDIO,DES_ESTUDIO,ACTIVO) values ('0000001','Estudio Interno BBVA','1');
INSERT INTO VISPOD.TIIVS_ESTUDIO (COD_ESTUDIO,DES_ESTUDIO,ACTIVO) values ('0000002','Estudio Zambrano','1');
INSERT INTO VISPOD.TIIVS_ESTUDIO (COD_ESTUDIO,DES_ESTUDIO,ACTIVO) values ('0000003','Estudio Corporación Bramilsa SAC','1');

-- TIIVS_GRUPO --
INSERT INTO VISPOD.TIIVS_GRUPO (COD_GRUPO,DES_GRUPO) values ('0000001','OFICINA');
INSERT INTO VISPOD.TIIVS_GRUPO (COD_GRUPO,DES_GRUPO) values ('0000002','ABOGADO');
INSERT INTO VISPOD.TIIVS_GRUPO (COD_GRUPO,DES_GRUPO) values ('0000003','SERVICIOS JURIDICOS');

-- TIIVS_TIPO_SOLICITUD --
INSERT INTO VISPOD.TIIVS_TIPO_SOLICITUD (COD_TIP_SOLIC,DES_TIP_SERVICIO,ACTIVO) VALUES ('0000001', 'OPERACIONES DINERARIAS MENORES A 1 UIT PER NATURAL', '1');
INSERT INTO VISPOD.TIIVS_TIPO_SOLICITUD (COD_TIP_SOLIC,DES_TIP_SERVICIO,ACTIVO) VALUES ('0000002', 'OPERACIONES DINERARIAS MAYORES A 1 UIT PER NATURAL', '1');
INSERT INTO VISPOD.TIIVS_TIPO_SOLICITUD (COD_TIP_SOLIC,DES_TIP_SERVICIO,ACTIVO) VALUES ('0000003', 'CLIENTES FALLECIDOS CON TESTAMENTO', '1');
INSERT INTO VISPOD.TIIVS_TIPO_SOLICITUD (COD_TIP_SOLIC,DES_TIP_SERVICIO,ACTIVO) VALUES ('0000004', 'CLIENTES FALLECIDOS SIN TESTAMENTO', '1');
INSERT INTO VISPOD.TIIVS_TIPO_SOLICITUD (COD_TIP_SOLIC,DES_TIP_SERVICIO,ACTIVO) VALUES ('0000005', 'DISPOSICION DE BIENES DE MENORES DE EDAD', '1');
INSERT INTO VISPOD.TIIVS_TIPO_SOLICITUD (COD_TIP_SOLIC,DES_TIP_SERVICIO,ACTIVO) VALUES ('0000006', 'DISPOSICION DE BIENES DE INCAPACES', '1');
INSERT INTO VISPOD.TIIVS_TIPO_SOLICITUD (COD_TIP_SOLIC,DES_TIP_SERVICIO,ACTIVO) VALUES ('0000007', 'REGISTRO EN EL SISTEMA DE APODERADOS', '1');
INSERT INTO VISPOD.TIIVS_TIPO_SOLICITUD (COD_TIP_SOLIC,DES_TIP_SERVICIO,ACTIVO) VALUES ('0000008', 'OPERACIONES DE PERSONA JURIDICA CUALQUIER MONTO', '1');
INSERT INTO VISPOD.TIIVS_TIPO_SOLICITUD (COD_TIP_SOLIC,DES_TIP_SERVICIO,ACTIVO) VALUES ('0000009', 'CANCELA DEPOSITO SOCIEDAD FORMACION NO CONSTITUIDA', '1');
INSERT INTO VISPOD.TIIVS_TIPO_SOLICITUD (COD_TIP_SOLIC,DES_TIP_SERVICIO,ACTIVO) VALUES ('0000010', 'COBRO SUBSIDIO POR PODER PAGO ELECTRONICO O CHEQU', '1');

-- TIIVS_OPERACION_BANCARIA --
INSERT INTO "VISPOD"."TIIVS_OPERACION_BANCARIA" (COD_OPER_BAN, DES_OPER_BAN, ACTIVO) VALUES ('0000001', 'PAGO DE CHEQUE', '1');
INSERT INTO "VISPOD"."TIIVS_OPERACION_BANCARIA" (COD_OPER_BAN, DES_OPER_BAN, ACTIVO) VALUES ('0000002', 'VENTA DE ACCIONES', '1');
INSERT INTO "VISPOD"."TIIVS_OPERACION_BANCARIA" (COD_OPER_BAN, DES_OPER_BAN, ACTIVO) VALUES ('0000003', 'RETIRO DE FONDOS', '1');
INSERT INTO "VISPOD"."TIIVS_OPERACION_BANCARIA" (COD_OPER_BAN, DES_OPER_BAN, ACTIVO) VALUES ('0000004', 'RESCATE DE FONDOS MUTUOS', '1');
INSERT INTO "VISPOD"."TIIVS_OPERACION_BANCARIA" (COD_OPER_BAN, DES_OPER_BAN, ACTIVO) VALUES ('0000005', 'PAGO ELECTRÓNICO: PAGO DE SUBSIDIOS, PAGO DE PENSI', '1');
INSERT INTO "VISPOD"."TIIVS_OPERACION_BANCARIA" (COD_OPER_BAN, DES_OPER_BAN, ACTIVO) VALUES ('0000006', 'SOLICITAR PRÉSTAMOS', '1');
INSERT INTO "VISPOD"."TIIVS_OPERACION_BANCARIA" (COD_OPER_BAN, DES_OPER_BAN, ACTIVO) VALUES ('0000007', 'EMITIR PAGARÉS', '1');
INSERT INTO "VISPOD"."TIIVS_OPERACION_BANCARIA" (COD_OPER_BAN, DES_OPER_BAN, ACTIVO) VALUES ('0000008', 'OTORGAR FIANZA', '1');
INSERT INTO "VISPOD"."TIIVS_OPERACION_BANCARIA" (COD_OPER_BAN, DES_OPER_BAN, ACTIVO) VALUES ('0000009', 'GRAVAR BIENES MUEBLES o GARANTIA MOBILIARIA', '1');
INSERT INTO "VISPOD"."TIIVS_OPERACION_BANCARIA" (COD_OPER_BAN, DES_OPER_BAN, ACTIVO) VALUES ('0000010', 'SOLICITUD DE INFORMACIÓN', '1');
INSERT INTO "VISPOD"."TIIVS_OPERACION_BANCARIA" (COD_OPER_BAN, DES_OPER_BAN, ACTIVO) VALUES ('0000011', 'COBRO DE SUBSIDIOS ESSALUD', '1');
INSERT INTO "VISPOD"."TIIVS_OPERACION_BANCARIA" (COD_OPER_BAN, DES_OPER_BAN, ACTIVO) VALUES ('0000012', 'Otros', '1');




COMMIT;
