package com.hildebrando.visado.modelo;
// Generated 13-jun-2012 10:20:15 by Hibernate Tools 3.4.0.CR1



/**
 * QrtzLocks generated by hbm2java
 */
public class QrtzLocks  implements java.io.Serializable {


     private String lockName;

    public QrtzLocks() {
    }

    public QrtzLocks(String lockName) {
       this.lockName = lockName;
    }
   
    public String getLockName() {
        return this.lockName;
    }
    
    public void setLockName(String lockName) {
        this.lockName = lockName;
    }




}


