package com.hildebrando.visado.modelo;
// Generated 13-jun-2012 10:20:15 by Hibernate Tools 3.4.0.CR1



/**
 * QrtzJobListeners generated by hbm2java
 */
public class QrtzJobListeners  implements java.io.Serializable {


     private QrtzJobListenersId id;
     private QrtzJobDetails qrtzJobDetails;

    public QrtzJobListeners() {
    }

    public QrtzJobListeners(QrtzJobListenersId id, QrtzJobDetails qrtzJobDetails) {
       this.id = id;
       this.qrtzJobDetails = qrtzJobDetails;
    }
   
    public QrtzJobListenersId getId() {
        return this.id;
    }
    
    public void setId(QrtzJobListenersId id) {
        this.id = id;
    }
    public QrtzJobDetails getQrtzJobDetails() {
        return this.qrtzJobDetails;
    }
    
    public void setQrtzJobDetails(QrtzJobDetails qrtzJobDetails) {
        this.qrtzJobDetails = qrtzJobDetails;
    }




}


