package com.hildebrando.visado.modelo;
// Generated 13-jun-2012 10:20:15 by Hibernate Tools 3.4.0.CR1


import java.sql.Blob;
import java.util.HashSet;
import java.util.Set;

/**
 * QrtzJobDetails generated by hbm2java
 */
public class QrtzJobDetails  implements java.io.Serializable {

	 private static final long serialVersionUID = 1L;
	 
	 private int item;
     private QrtzJobDetailsId id;
     private String description;
     private String jobClassName;
     private String isDurable;
     private String isVolatile;
     private String isStateful;
     private String requestsRecovery;
     private Blob jobData;
     private Set qrtzTriggerses = new HashSet(0);
     private Set qrtzJobListenerses = new HashSet(0);

    public int getItem() {
		return item;
	}


	public void setItem(int item) {
		this.item = item;
	}


	public QrtzJobDetails() {
    }

	
    public QrtzJobDetails(QrtzJobDetailsId id, String jobClassName, String isDurable, String isVolatile, String isStateful, String requestsRecovery) {
        this.id = id;
        this.jobClassName = jobClassName;
        this.isDurable = isDurable;
        this.isVolatile = isVolatile;
        this.isStateful = isStateful;
        this.requestsRecovery = requestsRecovery;
    }
    public QrtzJobDetails(QrtzJobDetailsId id, String description, String jobClassName, String isDurable, String isVolatile, String isStateful, String requestsRecovery, Blob jobData, Set qrtzTriggerses, Set qrtzJobListenerses) {
       this.id = id;
       this.description = description;
       this.jobClassName = jobClassName;
       this.isDurable = isDurable;
       this.isVolatile = isVolatile;
       this.isStateful = isStateful;
       this.requestsRecovery = requestsRecovery;
       this.jobData = jobData;
       this.qrtzTriggerses = qrtzTriggerses;
       this.qrtzJobListenerses = qrtzJobListenerses;
    }
   
    public QrtzJobDetailsId getId() {
        return this.id;
    }
    
    public void setId(QrtzJobDetailsId id) {
        this.id = id;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getJobClassName() {
        return this.jobClassName;
    }
    
    public void setJobClassName(String jobClassName) {
        this.jobClassName = jobClassName;
    }
    public String getIsDurable() {
        return this.isDurable;
    }
    
    public void setIsDurable(String isDurable) {
        this.isDurable = isDurable;
    }
    public String getIsVolatile() {
        return this.isVolatile;
    }
    
    public void setIsVolatile(String isVolatile) {
        this.isVolatile = isVolatile;
    }
    public String getIsStateful() {
        return this.isStateful;
    }
    
    public void setIsStateful(String isStateful) {
        this.isStateful = isStateful;
    }
    public String getRequestsRecovery() {
        return this.requestsRecovery;
    }
    
    public void setRequestsRecovery(String requestsRecovery) {
        this.requestsRecovery = requestsRecovery;
    }
    public Blob getJobData() {
        return this.jobData;
    }
    
    public void setJobData(Blob jobData) {
        this.jobData = jobData;
    }
    public Set getQrtzTriggerses() {
        return this.qrtzTriggerses;
    }
    
    public void setQrtzTriggerses(Set qrtzTriggerses) {
        this.qrtzTriggerses = qrtzTriggerses;
    }
    public Set getQrtzJobListenerses() {
        return this.qrtzJobListenerses;
    }
    
    public void setQrtzJobListenerses(Set qrtzJobListenerses) {
        this.qrtzJobListenerses = qrtzJobListenerses;
    }




}


