package com.hildebrando.visado.modelo;

// Generated 08/02/2013 10:59:59 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * TiivsTiempo generated by hbm2java
 */
public class TiivsTiempo implements java.io.Serializable {

	private int tiempoId;
	private int numeroDia;
	private int numeroMes;
	private String nombreMes;
	private int anio;
	private Date fechaFormato;

	public TiivsTiempo() {
	}

	public TiivsTiempo(int tiempoId) {
		this.tiempoId = tiempoId;
	}

	public TiivsTiempo(int tiempoId, int numeroDia,
			int numeroMes, String nombreMes, int anio,
			Date fechaFormato) {
		this.tiempoId = tiempoId;
		this.numeroDia = numeroDia;
		this.numeroMes = numeroMes;
		this.nombreMes = nombreMes;
		this.anio = anio;
		this.fechaFormato = fechaFormato;
	}

	public int getTiempoId() {
		return this.tiempoId;
	}

	public void setTiempoId(int tiempoId) {
		this.tiempoId = tiempoId;
	}

	public int getNumeroDia() {
		return this.numeroDia;
	}

	public void setNumeroDia(int numeroDia) {
		this.numeroDia = numeroDia;
	}

	public int getNumeroMes() {
		return this.numeroMes;
	}

	public void setNumeroMes(int numeroMes) {
		this.numeroMes = numeroMes;
	}

	public String getNombreMes() {
		return this.nombreMes;
	}

	public void setNombreMes(String nombreMes) {
		this.nombreMes = nombreMes;
	}

	public int getAnio() {
		return this.anio;
	}

	public void setAnio(int anio) {
		this.anio = anio;
	}

	public Date getFechaFormato() {
		return this.fechaFormato;
	}

	public void setFechaFormato(Date fechaFormato) {
		this.fechaFormato = fechaFormato;
	}

}
