package com.hildebrando.visado.modelo;

// Generated 05/12/2012 11:41:39 AM by Hibernate 
/**
 * TiivsSolicitudOperban generated by hbm2java
 */
public class TiivsSolicitudOperban implements java.io.Serializable {
    private String sItem;
	private TiivsSolicitudOperbanId id;
	private TiivsOperacionBancaria tiivsOperacionBancaria;
	private Double importe;
/*	private String moneda;*/
	
	private Double tipoCambio;
	private Double importeSoles;

	public TiivsSolicitudOperban() {
	}

	public TiivsSolicitudOperban(TiivsSolicitudOperbanId id,
			TiivsOperacionBancaria tiivsOperacionBancaria) {
		this.id = id;
		this.tiivsOperacionBancaria = tiivsOperacionBancaria;
	}

	public TiivsSolicitudOperban(TiivsSolicitudOperbanId id,
			TiivsOperacionBancaria tiivsOperacionBancaria, Double importe,
			/*String moneda*/ Double tipoCambio) {
		this.id = id;
		this.tiivsOperacionBancaria = tiivsOperacionBancaria;
		this.importe = importe;
		//this.moneda = moneda;
		this.tipoCambio = tipoCambio;
	}

	public TiivsSolicitudOperbanId getId() {
		return this.id;
	}

	public void setId(TiivsSolicitudOperbanId id) {
		this.id = id;
	}

	public TiivsOperacionBancaria getTiivsOperacionBancaria() {
		return this.tiivsOperacionBancaria;
	}

	public void setTiivsOperacionBancaria(
			TiivsOperacionBancaria tiivsOperacionBancaria) {
		this.tiivsOperacionBancaria = tiivsOperacionBancaria;
	}

	public Double getImporte() {
		return this.importe;
	}

	public void setImporte(Double importe) {
		this.importe = importe;
	}

	
	public Double getTipoCambio() {
		return this.tipoCambio;
	}

	public void setTipoCambio(Double tipoCambio) {
		this.tipoCambio = tipoCambio;
	}

	public Double getImporteSoles() {
		return importeSoles;
	}

	public void setImporteSoles(Double importeSoles) {
		this.importeSoles = importeSoles;
	}

	public String getsItem() {
		return sItem;
	}

	public void setsItem(String sItem) {
		this.sItem = sItem;
	}

	

}
