package com.hildebrando.visado.modelo;

// Generated 05/12/2012 11:41:39 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TiivsTarea generated by hbm2java
 */
public class TiivsTarea implements java.io.Serializable {

	private String codTarea;
	private String desTarea;
	private Set tiivsGrupos = new HashSet(0);

	public TiivsTarea() {
	}

	public TiivsTarea(String codTarea, String desTarea) {
		this.codTarea = codTarea;
		this.desTarea = desTarea;
	}

	public TiivsTarea(String codTarea, String desTarea, Set tiivsGrupos) {
		this.codTarea = codTarea;
		this.desTarea = desTarea;
		this.tiivsGrupos = tiivsGrupos;
	}

	public String getCodTarea() {
		return this.codTarea;
	}

	public void setCodTarea(String codTarea) {
		this.codTarea = codTarea;
	}

	public String getDesTarea() {
		return this.desTarea;
	}

	public void setDesTarea(String desTarea) {
		this.desTarea = desTarea;
	}

	public Set getTiivsGrupos() {
		return this.tiivsGrupos;
	}

	public void setTiivsGrupos(Set tiivsGrupos) {
		this.tiivsGrupos = tiivsGrupos;
	}

}
