package com.hildebrando.visado.modelo;

// Generated 07/11/2012 02:39:40 PM by Hibernate Tools 3.4.0.CR1

/**
 * TiivsPoderdante generated by hbm2java
 */
public class TiivsPoderdante implements java.io.Serializable {

	private TiivsPoderdanteId id;
	private TiivsSolicitud tiivsSolicitud;

	public TiivsPoderdante() {
	}

	public TiivsPoderdante(TiivsPoderdanteId id) {
		this.id = id;
	}

	public TiivsPoderdante(TiivsPoderdanteId id, TiivsSolicitud tiivsSolicitud) {
		this.id = id;
		this.tiivsSolicitud = tiivsSolicitud;
	}

	public TiivsPoderdanteId getId() {
		return this.id;
	}

	public void setId(TiivsPoderdanteId id) {
		this.id = id;
	}

	public TiivsSolicitud getTiivsSolicitud() {
		return this.tiivsSolicitud;
	}

	public void setTiivsSolicitud(TiivsSolicitud tiivsSolicitud) {
		this.tiivsSolicitud = tiivsSolicitud;
	}

}
