package com.hildebrando.visado.modelo;

// Generated 07/11/2012 02:39:40 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TiivsTarea generated by hbm2java
 */
public class TiivsTarea implements java.io.Serializable {

	private String codTarea;
	private String desTarea;
	private Set tiivsTareaGrupos = new HashSet(0);

	public TiivsTarea() {
	}

	public TiivsTarea(String codTarea, String desTarea) {
		this.codTarea = codTarea;
		this.desTarea = desTarea;
	}

	public TiivsTarea(String codTarea, String desTarea, Set tiivsTareaGrupos) {
		this.codTarea = codTarea;
		this.desTarea = desTarea;
		this.tiivsTareaGrupos = tiivsTareaGrupos;
	}

	public String getCodTarea() {
		return this.codTarea;
	}

	public void setCodTarea(String codTarea) {
		this.codTarea = codTarea;
	}

	public String getDesTarea() {
		return this.desTarea;
	}

	public void setDesTarea(String desTarea) {
		this.desTarea = desTarea;
	}

	public Set getTiivsTareaGrupos() {
		return this.tiivsTareaGrupos;
	}

	public void setTiivsTareaGrupos(Set tiivsTareaGrupos) {
		this.tiivsTareaGrupos = tiivsTareaGrupos;
	}

}
