package com.hildebrando.visado.modelo;

// Generated 10/12/2012 04:37:45 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TiivsEstudio generated by hbm2java
 */
public class TiivsEstudio implements java.io.Serializable {

	private String codEstudio;
	private String desEstudio;
	private Character activo;
	private Set<TiivsSolicitud> tiivsSolicituds = new HashSet<TiivsSolicitud>();
	private double costo;
	private String desActivo;

	public TiivsEstudio() {
	}

	public TiivsEstudio(String codEstudio) {
		this.codEstudio = codEstudio;
	}

	public TiivsEstudio(String codEstudio, String desEstudio, Character activo,
			Set tiivsSolicituds) {
		this.codEstudio = codEstudio;
		this.desEstudio = desEstudio;
		this.activo = activo;
		this.tiivsSolicituds = tiivsSolicituds;
	}

	public String getCodEstudio() {
		return this.codEstudio;
	}

	public void setCodEstudio(String codEstudio) {
		this.codEstudio = codEstudio;
	}

	public String getDesEstudio() {
		return this.desEstudio;
	}

	public void setDesEstudio(String desEstudio) {
		this.desEstudio = desEstudio;
	}

	public Character getActivo() {
		return this.activo;
	}

	public void setActivo(Character activo) {
		this.activo = activo;
	}

	public Set getTiivsSolicituds() {
		return this.tiivsSolicituds;
	}

	public void setTiivsSolicituds(Set tiivsSolicituds) {
		this.tiivsSolicituds = tiivsSolicituds;
	}

	public double getCosto() {
		return costo;
	}

	public void setCosto(double costo) {
		this.costo = costo;
	}

	public String getDesActivo() {
		return desActivo;
	}

	public void setDesActivo(String desActivo) {
		this.desActivo = desActivo;
	}
}
