package com.hildebrando.visado.modelo;

// Generated 07/11/2012 02:39:40 PM by Hibernate Tools 3.4.0.CR1

/**
 * TiivsSolicitudOperban generated by hbm2java
 */
public class TiivsSolicitudOperban implements java.io.Serializable {

	private TiivsSolicitudOperbanId id;
	private TiivsOperacionBancaria tiivsOperacionBancaria;

	public TiivsSolicitudOperban() {
	}

	public TiivsSolicitudOperban(TiivsSolicitudOperbanId id,
			TiivsOperacionBancaria tiivsOperacionBancaria) {
		this.id = id;
		this.tiivsOperacionBancaria = tiivsOperacionBancaria;
	}

	public TiivsSolicitudOperbanId getId() {
		return this.id;
	}

	public void setId(TiivsSolicitudOperbanId id) {
		this.id = id;
	}

	public TiivsOperacionBancaria getTiivsOperacionBancaria() {
		return this.tiivsOperacionBancaria;
	}

	public void setTiivsOperacionBancaria(
			TiivsOperacionBancaria tiivsOperacionBancaria) {
		this.tiivsOperacionBancaria = tiivsOperacionBancaria;
	}

}
