package com.hildebrando.visado.modelo;

// Generated 07/11/2012 02:39:40 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TiivsTipoDocumento generated by hbm2java
 */
public class TiivsTipoDocumento implements java.io.Serializable {

	private String codDoc;
	private TiivsTipoServicio tiivsTipoServicio;
	private String desDoc;
	private char activo;
	private char obligatorio;
	private Set tiivsAnexoSolicituds = new HashSet(0);

	public TiivsTipoDocumento() {
	}

	public TiivsTipoDocumento(String codDoc,
			TiivsTipoServicio tiivsTipoServicio, String desDoc, char activo,
			char obligatorio) {
		this.codDoc = codDoc;
		this.tiivsTipoServicio = tiivsTipoServicio;
		this.desDoc = desDoc;
		this.activo = activo;
		this.obligatorio = obligatorio;
	}

	public TiivsTipoDocumento(String codDoc,
			TiivsTipoServicio tiivsTipoServicio, String desDoc, char activo,
			char obligatorio, Set tiivsAnexoSolicituds) {
		this.codDoc = codDoc;
		this.tiivsTipoServicio = tiivsTipoServicio;
		this.desDoc = desDoc;
		this.activo = activo;
		this.obligatorio = obligatorio;
		this.tiivsAnexoSolicituds = tiivsAnexoSolicituds;
	}

	public String getCodDoc() {
		return this.codDoc;
	}

	public void setCodDoc(String codDoc) {
		this.codDoc = codDoc;
	}

	public TiivsTipoServicio getTiivsTipoServicio() {
		return this.tiivsTipoServicio;
	}

	public void setTiivsTipoServicio(TiivsTipoServicio tiivsTipoServicio) {
		this.tiivsTipoServicio = tiivsTipoServicio;
	}

	public String getDesDoc() {
		return this.desDoc;
	}

	public void setDesDoc(String desDoc) {
		this.desDoc = desDoc;
	}

	public char getActivo() {
		return this.activo;
	}

	public void setActivo(char activo) {
		this.activo = activo;
	}

	public char getObligatorio() {
		return this.obligatorio;
	}

	public void setObligatorio(char obligatorio) {
		this.obligatorio = obligatorio;
	}

	public Set getTiivsAnexoSolicituds() {
		return this.tiivsAnexoSolicituds;
	}

	public void setTiivsAnexoSolicituds(Set tiivsAnexoSolicituds) {
		this.tiivsAnexoSolicituds = tiivsAnexoSolicituds;
	}

}
