package com.hildebrando.visado.modelo;

// Generated 05/12/2012 02:50:20 PM by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * TiivsPersona generated by hbm2java
 */
public class TiivsPersona implements java.io.Serializable {

	private int codPer;
	private String codCen;
	private String tipDoi;
	private String numDoi;
	private String nombre;
	private String apePat;
	private String apeMat;
	private String numCel;
	private String email;
	private String usuarioRegistro;
	private Timestamp fechaRegistro;

	
	//Datos del Bean /*SAMIRA*/
	private String tipPartic;
	private String clasifPer;
	private String clasifPerOtro;
	
	private String sDesctipPartic;
	private String sDescclasifPer;
	private String sDesctipDoi;
	private Integer idAgrupacion;
	
	private String nombreCompletoMayuscula;

	private Set tiivsRevocados = new HashSet(0);
	private Set<TiivsAgrupacionPersona> tiivsAgrupacionPersonas = new HashSet<TiivsAgrupacionPersona>();

	public TiivsPersona() {
	}

	public TiivsPersona(int codPer) {
		this.codPer = codPer;
	}

	public TiivsPersona(int codPer, String codCen, String tipDoi,
			String numDoi, String nombre, String apePat, String apeMat,
			String numCel, String email, String usuarioRegistro,
			Timestamp fechaRegistro, Set<TiivsAgrupacionPersona> tiivsAgrupacionPersonas) {
		this.codPer = codPer;
		this.codCen = codCen;
		this.tipDoi = tipDoi;
		this.numDoi = numDoi;
		this.nombre = nombre;
		this.apePat = apePat;
		this.apeMat = apeMat;
		this.numCel = numCel;
		this.email = email;
		this.usuarioRegistro = usuarioRegistro;
		this.fechaRegistro = fechaRegistro;
		this.tiivsAgrupacionPersonas = tiivsAgrupacionPersonas;
	}

	public int getCodPer() {
		return this.codPer;
	}

	public void setCodPer(int codPer) {
		this.codPer = codPer;
	}

	public String getCodCen() {
		return this.codCen;
	}

	public void setCodCen(String codCen) {
		this.codCen = codCen;
	}

	public String getTipDoi() {
		return this.tipDoi;
	}

	public void setTipDoi(String tipDoi) {
		this.tipDoi = tipDoi;
	}

	public String getNumDoi() {
		return this.numDoi;
	}

	public void setNumDoi(String numDoi) {
		this.numDoi = numDoi;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApePat() {
		return this.apePat;
	}

	public void setApePat(String apePat) {
		this.apePat = apePat;
	}

	public String getApeMat() {
		return this.apeMat;
	}

	public void setApeMat(String apeMat) {
		this.apeMat = apeMat;
	}

	public String getNumCel() {
		return this.numCel;
	}

	public void setNumCel(String numCel) {
		this.numCel = numCel;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}
	
	public String getUsuarioRegistro() {
		return this.usuarioRegistro;
	}

	public void setUsuarioRegistro(String usuarioRegistro) {
		this.usuarioRegistro = usuarioRegistro;
	}

	public Timestamp getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Timestamp fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	public Set<TiivsAgrupacionPersona> getTiivsAgrupacionPersonas() {
		return this.tiivsAgrupacionPersonas;
	}

	public void setTiivsAgrupacionPersonas(Set<TiivsAgrupacionPersona> tiivsAgrupacionPersonas) {
		this.tiivsAgrupacionPersonas = tiivsAgrupacionPersonas;
	}

	public String getTipPartic() {
		return tipPartic;
	}

	public void setTipPartic(String tipPartic) {
		this.tipPartic = tipPartic;
	}

	public String getClasifPer() {
		return clasifPer;
	}

	public void setClasifPer(String clasifPer) {
		this.clasifPer = clasifPer;
	}

	public String getClasifPerOtro() {
		return clasifPerOtro;
	}

	public void setClasifPerOtro(String clasifPerOtro) {
		this.clasifPerOtro = clasifPerOtro;
	}

	public String getsDesctipPartic() {
		return sDesctipPartic;
	}

	public void setsDesctipPartic(String sDesctipPartic) {
		this.sDesctipPartic = sDesctipPartic;
	}

	public String getsDescclasifPer() {
		return sDescclasifPer;
	}

	public void setsDescclasifPer(String sDescclasifPer) {
		this.sDescclasifPer = sDescclasifPer;
	}

	public String getsDesctipDoi() {
		return sDesctipDoi;
	}

	public void setsDesctipDoi(String sDesctipDoi) {
		this.sDesctipDoi = sDesctipDoi;
	}

	public void setNombreCompletoMayuscula(String nombreCompletoMayuscula) {
		this.nombreCompletoMayuscula = nombreCompletoMayuscula;
	}

	public String getNombreCompletoMayuscula() {
		return nombreCompletoMayuscula;
	}

	public Set getTiivsRevocados() {
		return tiivsRevocados;
	}

	public void setTiivsRevocados(Set tiivsRevocados) {
		this.tiivsRevocados = tiivsRevocados;
	}

	@Override
	public String toString() {
		return "TiivsPersona [codPer=" + this.codPer + ", codCen="
				+ this.codCen + ", tipDoi=" + this.tipDoi + ", numDoi="
				+ this.numDoi + ", nombre=" + this.nombre + ", apePat="
				+ this.apePat + ", apeMat=" + this.apeMat + ", numCel="
				+ this.numCel + ", email=" + this.email + ", usuarioRegistro="
				+ this.usuarioRegistro + ", fechaRegistro="
				+ this.fechaRegistro + ", tipPartic=" + this.tipPartic
				+ ", clasifPer=" + this.clasifPer + ", clasifPerOtro="
				+ this.clasifPerOtro + ", sDesctipPartic="
				+ this.sDesctipPartic + ", sDescclasifPer="
				+ this.sDescclasifPer + ", sDesctipDoi=" + this.sDesctipDoi
				+ ", nombreCompletoMayuscula=" + this.nombreCompletoMayuscula
				+ ", tiivsRevocados=" + this.tiivsRevocados
				+ ", tiivsAgrupacionPersonas=" + this.tiivsAgrupacionPersonas
				+ "]";
	}

	public void setIdAgrupacion(Integer idAgrupacion) {
		this.idAgrupacion = idAgrupacion;
		
	}

	public Integer getIdAgrupacion() {
		return idAgrupacion;
	}
	
	
	
	
	
}
