package com.hildebrando.visado.modelo;

// Generated 12/12/2012 12:08:20 PM by Hibernate Tools 3.4.0.CR1

/**
 * TiivsSolicitudNivelId generated by hbm2java
 */
public class TiivsSolicitudNivelId implements java.io.Serializable {

	private String codSoli;
	private String codNiv;

	public TiivsSolicitudNivelId() {
	}

	public TiivsSolicitudNivelId(String codSoli, String codNiv) {
		this.codSoli = codSoli;
		this.codNiv = codNiv;
	}

	public String getCodSoli() {
		return this.codSoli;
	}

	public void setCodSoli(String codSoli) {
		this.codSoli = codSoli;
	}

	public String getCodNiv() {
		return this.codNiv;
	}

	public void setCodNiv(String codNiv) {
		this.codNiv = codNiv;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TiivsSolicitudNivelId))
			return false;
		TiivsSolicitudNivelId castOther = (TiivsSolicitudNivelId) other;

		return ((this.getCodSoli() == castOther.getCodSoli()) || (this
				.getCodSoli() != null && castOther.getCodSoli() != null && this
				.getCodSoli().equals(castOther.getCodSoli())))
				&& ((this.getCodNiv() == castOther.getCodNiv()) || (this
						.getCodNiv() != null && castOther.getCodNiv() != null && this
						.getCodNiv().equals(castOther.getCodNiv())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCodSoli() == null ? 0 : this.getCodSoli().hashCode());
		result = 37 * result
				+ (getCodNiv() == null ? 0 : this.getCodNiv().hashCode());
		return result;
	}

}
