package com.hildebrando.visado.modelo;

// Generated 12/12/2012 12:08:20 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * TiivsNivelId generated by hbm2java
 */
public class TiivsNivelId implements java.io.Serializable {

	private Integer id;
	private String codNiv;
	private String desNiv;
	private Integer rangoInicio;
	private Integer rangoFin;
	private String moneda;
	private Date fechaReg;
	private String usuarioReg;
	private Date fechaAct;
	private String usuarioAct;
	private BigDecimal estado;

	public TiivsNivelId() {
	}

	public TiivsNivelId(Integer id, String codNiv, String desNiv,
			Integer rangoInicio, Integer rangoFin, String moneda,
			Date fechaReg, String usuarioReg, Date fechaAct, String usuarioAct,
			BigDecimal estado) {
		this.id = id;
		this.codNiv = codNiv;
		this.desNiv = desNiv;
		this.rangoInicio = rangoInicio;
		this.rangoFin = rangoFin;
		this.moneda = moneda;
		this.fechaReg = fechaReg;
		this.usuarioReg = usuarioReg;
		this.fechaAct = fechaAct;
		this.usuarioAct = usuarioAct;
		this.estado = estado;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCodNiv() {
		return this.codNiv;
	}

	public void setCodNiv(String codNiv) {
		this.codNiv = codNiv;
	}

	public String getDesNiv() {
		return this.desNiv;
	}

	public void setDesNiv(String desNiv) {
		this.desNiv = desNiv;
	}

	public Integer getRangoInicio() {
		return this.rangoInicio;
	}

	public void setRangoInicio(Integer rangoInicio) {
		this.rangoInicio = rangoInicio;
	}

	public Integer getRangoFin() {
		return this.rangoFin;
	}

	public void setRangoFin(Integer rangoFin) {
		this.rangoFin = rangoFin;
	}

	public String getMoneda() {
		return this.moneda;
	}

	public void setMoneda(String moneda) {
		this.moneda = moneda;
	}

	public Date getFechaReg() {
		return this.fechaReg;
	}

	public void setFechaReg(Date fechaReg) {
		this.fechaReg = fechaReg;
	}

	public String getUsuarioReg() {
		return this.usuarioReg;
	}

	public void setUsuarioReg(String usuarioReg) {
		this.usuarioReg = usuarioReg;
	}

	public Date getFechaAct() {
		return this.fechaAct;
	}

	public void setFechaAct(Date fechaAct) {
		this.fechaAct = fechaAct;
	}

	public String getUsuarioAct() {
		return this.usuarioAct;
	}

	public void setUsuarioAct(String usuarioAct) {
		this.usuarioAct = usuarioAct;
	}

	public BigDecimal getEstado() {
		return this.estado;
	}

	public void setEstado(BigDecimal estado) {
		this.estado = estado;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TiivsNivelId))
			return false;
		TiivsNivelId castOther = (TiivsNivelId) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getCodNiv() == castOther.getCodNiv()) || (this
						.getCodNiv() != null && castOther.getCodNiv() != null && this
						.getCodNiv().equals(castOther.getCodNiv())))
				&& ((this.getDesNiv() == castOther.getDesNiv()) || (this
						.getDesNiv() != null && castOther.getDesNiv() != null && this
						.getDesNiv().equals(castOther.getDesNiv())))
				&& ((this.getRangoInicio() == castOther.getRangoInicio()) || (this
						.getRangoInicio() != null
						&& castOther.getRangoInicio() != null && this
						.getRangoInicio().equals(castOther.getRangoInicio())))
				&& ((this.getRangoFin() == castOther.getRangoFin()) || (this
						.getRangoFin() != null
						&& castOther.getRangoFin() != null && this
						.getRangoFin().equals(castOther.getRangoFin())))
				&& ((this.getMoneda() == castOther.getMoneda()) || (this
						.getMoneda() != null && castOther.getMoneda() != null && this
						.getMoneda().equals(castOther.getMoneda())))
				&& ((this.getFechaReg() == castOther.getFechaReg()) || (this
						.getFechaReg() != null
						&& castOther.getFechaReg() != null && this
						.getFechaReg().equals(castOther.getFechaReg())))
				&& ((this.getUsuarioReg() == castOther.getUsuarioReg()) || (this
						.getUsuarioReg() != null
						&& castOther.getUsuarioReg() != null && this
						.getUsuarioReg().equals(castOther.getUsuarioReg())))
				&& ((this.getFechaAct() == castOther.getFechaAct()) || (this
						.getFechaAct() != null
						&& castOther.getFechaAct() != null && this
						.getFechaAct().equals(castOther.getFechaAct())))
				&& ((this.getUsuarioAct() == castOther.getUsuarioAct()) || (this
						.getUsuarioAct() != null
						&& castOther.getUsuarioAct() != null && this
						.getUsuarioAct().equals(castOther.getUsuarioAct())))
				&& ((this.getEstado() == castOther.getEstado()) || (this
						.getEstado() != null && castOther.getEstado() != null && this
						.getEstado().equals(castOther.getEstado())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getCodNiv() == null ? 0 : this.getCodNiv().hashCode());
		result = 37 * result
				+ (getDesNiv() == null ? 0 : this.getDesNiv().hashCode());
		result = 37
				* result
				+ (getRangoInicio() == null ? 0 : this.getRangoInicio()
						.hashCode());
		result = 37 * result
				+ (getRangoFin() == null ? 0 : this.getRangoFin().hashCode());
		result = 37 * result
				+ (getMoneda() == null ? 0 : this.getMoneda().hashCode());
		result = 37 * result
				+ (getFechaReg() == null ? 0 : this.getFechaReg().hashCode());
		result = 37
				* result
				+ (getUsuarioReg() == null ? 0 : this.getUsuarioReg()
						.hashCode());
		result = 37 * result
				+ (getFechaAct() == null ? 0 : this.getFechaAct().hashCode());
		result = 37
				* result
				+ (getUsuarioAct() == null ? 0 : this.getUsuarioAct()
						.hashCode());
		result = 37 * result
				+ (getEstado() == null ? 0 : this.getEstado().hashCode());
		return result;
	}

}
