package com.hildebrando.visado.modelo;

// Generated 07/11/2012 02:39:40 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TiivsTerritorio generated by hbm2java
 */
public class TiivsTerritorio implements java.io.Serializable {

	private String codTer;
	private String desTer;
	private Set tiivsOficinas = new HashSet(0);

	public TiivsTerritorio() {
	}

	public TiivsTerritorio(String codTer, String desTer) {
		this.codTer = codTer;
		this.desTer = desTer;
	}

	public TiivsTerritorio(String codTer, String desTer, Set tiivsOficinas) {
		this.codTer = codTer;
		this.desTer = desTer;
		this.tiivsOficinas = tiivsOficinas;
	}

	public String getCodTer() {
		return this.codTer;
	}

	public void setCodTer(String codTer) {
		this.codTer = codTer;
	}

	public String getDesTer() {
		return this.desTer;
	}

	public void setDesTer(String desTer) {
		this.desTer = desTer;
	}

	public Set getTiivsOficinas() {
		return this.tiivsOficinas;
	}

	public void setTiivsOficinas(Set tiivsOficinas) {
		this.tiivsOficinas = tiivsOficinas;
	}

}
