package com.hildebrando.visado.modelo;

// Generated 05/12/2012 11:17:13 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TiivsPersona generated by hbm2java
 */
public class TiivsPersona implements java.io.Serializable {

	private int codPer;
	private String codCen;
	private String tipDoi;
	private String numDoi;
	private String nombre;
	private String apePat;
	private String apeMat;
	private String numCel;
	private String email;
	private Set tiivsAgrupacionPersonas = new HashSet(0);

	public TiivsPersona() {
	}

	public TiivsPersona(int codPer) {
		this.codPer = codPer;
	}

	public TiivsPersona(int codPer, String codCen, String tipDoi,
			String numDoi, String nombre, String apePat, String apeMat,
			String numCel, String email, Set tiivsAgrupacionPersonas) {
		this.codPer = codPer;
		this.codCen = codCen;
		this.tipDoi = tipDoi;
		this.numDoi = numDoi;
		this.nombre = nombre;
		this.apePat = apePat;
		this.apeMat = apeMat;
		this.numCel = numCel;
		this.email = email;
		this.tiivsAgrupacionPersonas = tiivsAgrupacionPersonas;
	}

	public int getCodPer() {
		return this.codPer;
	}

	public void setCodPer(int codPer) {
		this.codPer = codPer;
	}

	public String getCodCen() {
		return this.codCen;
	}

	public void setCodCen(String codCen) {
		this.codCen = codCen;
	}

	public String getTipDoi() {
		return this.tipDoi;
	}

	public void setTipDoi(String tipDoi) {
		this.tipDoi = tipDoi;
	}

	public String getNumDoi() {
		return this.numDoi;
	}

	public void setNumDoi(String numDoi) {
		this.numDoi = numDoi;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApePat() {
		return this.apePat;
	}

	public void setApePat(String apePat) {
		this.apePat = apePat;
	}

	public String getApeMat() {
		return this.apeMat;
	}

	public void setApeMat(String apeMat) {
		this.apeMat = apeMat;
	}

	public String getNumCel() {
		return this.numCel;
	}

	public void setNumCel(String numCel) {
		this.numCel = numCel;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Set getTiivsAgrupacionPersonas() {
		return this.tiivsAgrupacionPersonas;
	}

	public void setTiivsAgrupacionPersonas(Set tiivsAgrupacionPersonas) {
		this.tiivsAgrupacionPersonas = tiivsAgrupacionPersonas;
	}

}
