package com.hildebrando.visado.modelo;

// Generated 05/12/2012 11:41:39 AM by Hibernate Tools 3.4.0.CR1

/**
 * TiivsSolicitudAgrupacionId generated by hbm2java
 */
public class TiivsSolicitudAgrupacionId implements java.io.Serializable {

	private String codSoli;
	private int numGrupo;

	public TiivsSolicitudAgrupacionId() {
	}

	public TiivsSolicitudAgrupacionId(String codSoli, int numGrupo) {
		this.codSoli = codSoli;
		this.numGrupo = numGrupo;
	}

	public String getCodSoli() {
		return this.codSoli;
	}

	public void setCodSoli(String codSoli) {
		this.codSoli = codSoli;
	}

	public int getNumGrupo() {
		return this.numGrupo;
	}

	public void setNumGrupo(int numGrupo) {
		this.numGrupo = numGrupo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TiivsSolicitudAgrupacionId))
			return false;
		TiivsSolicitudAgrupacionId castOther = (TiivsSolicitudAgrupacionId) other;

		return ((this.getCodSoli() == castOther.getCodSoli()) || (this
				.getCodSoli() != null && castOther.getCodSoli() != null && this
				.getCodSoli().equals(castOther.getCodSoli())))
				&& (this.getNumGrupo() == castOther.getNumGrupo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCodSoli() == null ? 0 : this.getCodSoli().hashCode());
		result = 37 * result + this.getNumGrupo();
		return result;
	}

}
