package com.hildebrando.visado.modelo;

// Generated 07/11/2012 02:39:40 PM by Hibernate Tools 3.4.0.CR1

/**
 * TiivsTareaGrupoId generated by hbm2java
 */
public class TiivsTareaGrupoId implements java.io.Serializable {

	private String codTarea;
	private String codGrupo;

	public TiivsTareaGrupoId() {
	}

	public TiivsTareaGrupoId(String codTarea, String codGrupo) {
		this.codTarea = codTarea;
		this.codGrupo = codGrupo;
	}

	public String getCodTarea() {
		return this.codTarea;
	}

	public void setCodTarea(String codTarea) {
		this.codTarea = codTarea;
	}

	public String getCodGrupo() {
		return this.codGrupo;
	}

	public void setCodGrupo(String codGrupo) {
		this.codGrupo = codGrupo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TiivsTareaGrupoId))
			return false;
		TiivsTareaGrupoId castOther = (TiivsTareaGrupoId) other;

		return ((this.getCodTarea() == castOther.getCodTarea()) || (this
				.getCodTarea() != null && castOther.getCodTarea() != null && this
				.getCodTarea().equals(castOther.getCodTarea())))
				&& ((this.getCodGrupo() == castOther.getCodGrupo()) || (this
						.getCodGrupo() != null
						&& castOther.getCodGrupo() != null && this
						.getCodGrupo().equals(castOther.getCodGrupo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCodTarea() == null ? 0 : this.getCodTarea().hashCode());
		result = 37 * result
				+ (getCodGrupo() == null ? 0 : this.getCodGrupo().hashCode());
		return result;
	}

}
