package com.hildebrando.visado.modelo;

// Generated 07/11/2012 02:39:40 PM by Hibernate Tools 3.4.0.CR1

/**
 * TiivsPoderdanteId generated by hbm2java
 */
public class TiivsPoderdanteId implements java.io.Serializable {

	private String codSoli;
	private String codPod;
	private String tipDocPoder;
	private String numDocPoder;

	public TiivsPoderdanteId() {
	}

	public TiivsPoderdanteId(String codSoli, String codPod, String tipDocPoder,
			String numDocPoder) {
		this.codSoli = codSoli;
		this.codPod = codPod;
		this.tipDocPoder = tipDocPoder;
		this.numDocPoder = numDocPoder;
	}

	public String getCodSoli() {
		return this.codSoli;
	}

	public void setCodSoli(String codSoli) {
		this.codSoli = codSoli;
	}

	public String getCodPod() {
		return this.codPod;
	}

	public void setCodPod(String codPod) {
		this.codPod = codPod;
	}

	public String getTipDocPoder() {
		return this.tipDocPoder;
	}

	public void setTipDocPoder(String tipDocPoder) {
		this.tipDocPoder = tipDocPoder;
	}

	public String getNumDocPoder() {
		return this.numDocPoder;
	}

	public void setNumDocPoder(String numDocPoder) {
		this.numDocPoder = numDocPoder;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TiivsPoderdanteId))
			return false;
		TiivsPoderdanteId castOther = (TiivsPoderdanteId) other;

		return ((this.getCodSoli() == castOther.getCodSoli()) || (this
				.getCodSoli() != null && castOther.getCodSoli() != null && this
				.getCodSoli().equals(castOther.getCodSoli())))
				&& ((this.getCodPod() == castOther.getCodPod()) || (this
						.getCodPod() != null && castOther.getCodPod() != null && this
						.getCodPod().equals(castOther.getCodPod())))
				&& ((this.getTipDocPoder() == castOther.getTipDocPoder()) || (this
						.getTipDocPoder() != null
						&& castOther.getTipDocPoder() != null && this
						.getTipDocPoder().equals(castOther.getTipDocPoder())))
				&& ((this.getNumDocPoder() == castOther.getNumDocPoder()) || (this
						.getNumDocPoder() != null
						&& castOther.getNumDocPoder() != null && this
						.getNumDocPoder().equals(castOther.getNumDocPoder())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCodSoli() == null ? 0 : this.getCodSoli().hashCode());
		result = 37 * result
				+ (getCodPod() == null ? 0 : this.getCodPod().hashCode());
		result = 37
				* result
				+ (getTipDocPoder() == null ? 0 : this.getTipDocPoder()
						.hashCode());
		result = 37
				* result
				+ (getNumDocPoder() == null ? 0 : this.getNumDocPoder()
						.hashCode());
		return result;
	}

}
