package com.hildebrando.visado.modelo;

// Generated 07/11/2012 02:39:40 PM by Hibernate Tools 3.4.0.CR1

/**
 * TiivsApoderdante generated by hbm2java
 */
public class TiivsApoderdante implements java.io.Serializable {

	private TiivsApoderdanteId id;
	private TiivsSolicitud tiivsSolicitud;

	public TiivsApoderdante() {
	}

	public TiivsApoderdante(TiivsApoderdanteId id) {
		this.id = id;
	}

	public TiivsApoderdante(TiivsApoderdanteId id, TiivsSolicitud tiivsSolicitud) {
		this.id = id;
		this.tiivsSolicitud = tiivsSolicitud;
	}

	public TiivsApoderdanteId getId() {
		return this.id;
	}

	public void setId(TiivsApoderdanteId id) {
		this.id = id;
	}

	public TiivsSolicitud getTiivsSolicitud() {
		return this.tiivsSolicitud;
	}

	public void setTiivsSolicitud(TiivsSolicitud tiivsSolicitud) {
		this.tiivsSolicitud = tiivsSolicitud;
	}

}
