package com.hildebrando.visado.modelo;

// Generated 05/12/2012 11:17:13 AM by Hibernate Tools 3.4.0.CR1

/**
 * TiivsMultitabla generated by hbm2java
 */
public class TiivsMultitabla implements java.io.Serializable {

	private TiivsMultitablaId id;
	private String valor1;
	private String valor2;
	private String valor3;
	private String valor4;
	private String valor5;
	private String valor6;
	private String valor7;

	public TiivsMultitabla() {
	}

	public TiivsMultitabla(TiivsMultitablaId id) {
		this.id = id;
	}

	public TiivsMultitabla(TiivsMultitablaId id, String valor1, String valor2,
			String valor3, String valor4, String valor5, String valor6,
			String valor7) {
		this.id = id;
		this.valor1 = valor1;
		this.valor2 = valor2;
		this.valor3 = valor3;
		this.valor4 = valor4;
		this.valor5 = valor5;
		this.valor6 = valor6;
		this.valor7 = valor7;
	}

	public TiivsMultitablaId getId() {
		return this.id;
	}

	public void setId(TiivsMultitablaId id) {
		this.id = id;
	}

	public String getValor1() {
		return this.valor1;
	}

	public void setValor1(String valor1) {
		this.valor1 = valor1;
	}

	public String getValor2() {
		return this.valor2;
	}

	public void setValor2(String valor2) {
		this.valor2 = valor2;
	}

	public String getValor3() {
		return this.valor3;
	}

	public void setValor3(String valor3) {
		this.valor3 = valor3;
	}

	public String getValor4() {
		return this.valor4;
	}

	public void setValor4(String valor4) {
		this.valor4 = valor4;
	}

	public String getValor5() {
		return this.valor5;
	}

	public void setValor5(String valor5) {
		this.valor5 = valor5;
	}

	public String getValor6() {
		return this.valor6;
	}

	public void setValor6(String valor6) {
		this.valor6 = valor6;
	}

	public String getValor7() {
		return this.valor7;
	}

	public void setValor7(String valor7) {
		this.valor7 = valor7;
	}

}
