package com.hildebrando.visado.modelo;

// Generated 05/12/2012 11:41:39 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TiivsSolicitudAgrupacion generated by hbm2java
 */
public class TiivsSolicitudAgrupacion implements java.io.Serializable {

	private TiivsSolicitudAgrupacionId id;
	private TiivsSolicitud tiivsSolicitud;
	private String activo;
	private Set tiivsAgrupacionPersonas = new HashSet(0);

	public TiivsSolicitudAgrupacion() {
	}

	public TiivsSolicitudAgrupacion(TiivsSolicitudAgrupacionId id,
			TiivsSolicitud tiivsSolicitud) {
		this.id = id;
		this.tiivsSolicitud = tiivsSolicitud;
	}

	public TiivsSolicitudAgrupacion(TiivsSolicitudAgrupacionId id,
			TiivsSolicitud tiivsSolicitud, String activo,
			Set tiivsAgrupacionPersonas) {
		this.id = id;
		this.tiivsSolicitud = tiivsSolicitud;
		this.activo = activo;
		this.tiivsAgrupacionPersonas = tiivsAgrupacionPersonas;
	}

	public TiivsSolicitudAgrupacionId getId() {
		return this.id;
	}

	public void setId(TiivsSolicitudAgrupacionId id) {
		this.id = id;
	}

	public TiivsSolicitud getTiivsSolicitud() {
		return this.tiivsSolicitud;
	}

	public void setTiivsSolicitud(TiivsSolicitud tiivsSolicitud) {
		this.tiivsSolicitud = tiivsSolicitud;
	}

	public String getActivo() {
		return this.activo;
	}

	public void setActivo(String activo) {
		this.activo = activo;
	}

	public Set getTiivsAgrupacionPersonas() {
		return this.tiivsAgrupacionPersonas;
	}

	public void setTiivsAgrupacionPersonas(Set tiivsAgrupacionPersonas) {
		this.tiivsAgrupacionPersonas = tiivsAgrupacionPersonas;
	}

}
