package com.hildebrando.visado.modelo;

// Generated 05/12/2012 11:17:13 AM by Hibernate Tools 3.4.0.CR1

/**
 * TiivsAgrupacionPersona generated by hbm2java
 */
public class TiivsAgrupacionPersona implements java.io.Serializable {

	private TiivsAgrupacionPersonaId id;
	private TiivsSolicitudAgrupacion tiivsSolicitudAgrupacion;
	private TiivsPersona tiivsPersona;
	private TiivsSolicitud tiivsSolicitud;

	public TiivsAgrupacionPersona() {
	}

	public TiivsAgrupacionPersona(TiivsAgrupacionPersonaId id) {
		this.id = id;
	}

	public TiivsAgrupacionPersona(TiivsAgrupacionPersonaId id,
			TiivsSolicitudAgrupacion tiivsSolicitudAgrupacion,
			TiivsPersona tiivsPersona, TiivsSolicitud tiivsSolicitud) {
		this.id = id;
		this.tiivsSolicitudAgrupacion = tiivsSolicitudAgrupacion;
		this.tiivsPersona = tiivsPersona;
		this.tiivsSolicitud = tiivsSolicitud;
	}

	public TiivsAgrupacionPersonaId getId() {
		return this.id;
	}

	public void setId(TiivsAgrupacionPersonaId id) {
		this.id = id;
	}

	public TiivsSolicitudAgrupacion getTiivsSolicitudAgrupacion() {
		return this.tiivsSolicitudAgrupacion;
	}

	public void setTiivsSolicitudAgrupacion(
			TiivsSolicitudAgrupacion tiivsSolicitudAgrupacion) {
		this.tiivsSolicitudAgrupacion = tiivsSolicitudAgrupacion;
	}

	public TiivsPersona getTiivsPersona() {
		return this.tiivsPersona;
	}

	public void setTiivsPersona(TiivsPersona tiivsPersona) {
		this.tiivsPersona = tiivsPersona;
	}

	public TiivsSolicitud getTiivsSolicitud() {
		return this.tiivsSolicitud;
	}

	public void setTiivsSolicitud(TiivsSolicitud tiivsSolicitud) {
		this.tiivsSolicitud = tiivsSolicitud;
	}

}
