package com.hildebrando.visado.modelo;

// Generated 08/01/2013 11:29:47 AM by Hibernate Tools 3.4.0.CR1

/**
 * TiivsDocumento generated by hbm2java
 */
public class TiivsDocumento implements java.io.Serializable {

	private String codDocumento;
	private String descripcion;
	private String activo;
	private TiivsTipoSolicDocumento tiivsTipoSolicDocumento;

	public TiivsDocumento() {
	}

	public TiivsDocumento(String codDocumento) {
		this.codDocumento = codDocumento;
	}

	public TiivsDocumento(String codDocumento, String descripcion,
			String activo, TiivsTipoSolicDocumento tiivsTipoSolicDocumento) {
		this.codDocumento = codDocumento;
		this.descripcion = descripcion;
		this.activo = activo;
		this.tiivsTipoSolicDocumento = tiivsTipoSolicDocumento;
	}

	public String getCodDocumento() {
		return this.codDocumento;
	}

	public void setCodDocumento(String codDocumento) {
		this.codDocumento = codDocumento;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getActivo() {
		return this.activo;
	}

	public void setActivo(String activo) {
		this.activo = activo;
	}

	public TiivsTipoSolicDocumento getTiivsTipoSolicDocumento() {
		return this.tiivsTipoSolicDocumento;
	}

	public void setTiivsTipoSolicDocumento(
			TiivsTipoSolicDocumento tiivsTipoSolicDocumento) {
		this.tiivsTipoSolicDocumento = tiivsTipoSolicDocumento;
	}

}
