package com.hildebrando.visado.modelo;

// Generated Feb 7, 2013 2:54:22 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TiivsRevocado generated by hbm2java
 */
public class TiivsRevocado implements java.io.Serializable {

	private int codRevocado;
	private TiivsPersona tiivsPersona;
	
	private String estado;
	private Date fechaRevocatoria;
	private Integer codAgrup;
	private String tipPartic;
	
	
	private String sDesctipPartic;
	private String sDesctipDoi;
	
	private String aliasArchivo;

	public TiivsRevocado() {
	}

	public TiivsRevocado(int codRevocado) {
		this.codRevocado = codRevocado;
	}

	public TiivsRevocado(int codRevocado, TiivsPersona tiivsPersona,
			String estado, Date fechaRevocatoria, Integer codAgrup,
			String tipPartic, String aliasArchivo) {
		this.codRevocado = codRevocado;
		this.tiivsPersona = tiivsPersona;
		this.estado = estado;
		this.fechaRevocatoria = fechaRevocatoria;
		this.codAgrup = codAgrup;
		this.tipPartic = tipPartic;
		this.aliasArchivo = aliasArchivo;
	}

	public int getCodRevocado() {
		return this.codRevocado;
	}

	public void setCodRevocado(int codRevocado) {
		this.codRevocado = codRevocado;
	}

	public TiivsPersona getTiivsPersona() {
		return this.tiivsPersona;
	}

	public void setTiivsPersona(TiivsPersona tiivsPersona) {
		this.tiivsPersona = tiivsPersona;
	}

	
	
	
	

	public Date getFechaRevocatoria() {
		return this.fechaRevocatoria;
	}

	public void setFechaRevocatoria(Date fechaRevocatoria) {
		this.fechaRevocatoria = fechaRevocatoria;
	}

	public Integer getCodAgrup() {
		return this.codAgrup;
	}

	public void setCodAgrup(Integer codAgrup) {
		this.codAgrup = codAgrup;
	}

	public String getTipPartic() {
		return this.tipPartic;
	}

	public void setTipPartic(String tipPartic) {
		this.tipPartic = tipPartic;
	}

	public String getEstado() {
		return estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getsDesctipPartic() {
		return sDesctipPartic;
	}

	public void setsDesctipPartic(String sDesctipPartic) {
		this.sDesctipPartic = sDesctipPartic;
	}

	public String getsDesctipDoi() {
		return sDesctipDoi;
	}

	public void setsDesctipDoi(String sDesctipDoi) {
		this.sDesctipDoi = sDesctipDoi;
	}

	public String getAliasArchivo() {
		return aliasArchivo;
	}

	public void setAliasArchivo(String aliasArchivo) {
		this.aliasArchivo = aliasArchivo;
	}

	

}
