package com.hildebrando.visado.modelo;

// Generated 05/12/2012 11:17:13 AM by Hibernate Tools 3.4.0.CR1

/**
 * TiivsTerritorio generated by hbm2java
 */
public class TiivsTerritorio implements java.io.Serializable {

	private String codTer;
	private String desTer;

	public TiivsTerritorio() {
	}

	public TiivsTerritorio(String codTer, String desTer) {
		this.codTer = codTer;
		this.desTer = desTer;
	}

	public String getCodTer() {
		return this.codTer;
	}

	public void setCodTer(String codTer) {
		this.codTer = codTer;
	}

	public String getDesTer() {
		return this.desTer;
	}

	public void setDesTer(String desTer) {
		this.desTer = desTer;
	}

}
