package com.hildebrando.visado.dto;

public class UsuarioLDAP2 {
    @SuppressWarnings("unused")
	private String nombreCompleto;
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IIVS.LDAPPERU2.CODUSU
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    private String codusu;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IIVS.LDAPPERU2.REGISTROU
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    private String registrou;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IIVS.LDAPPERU2.REGISTROP
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    private String registrop;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IIVS.LDAPPERU2.CODPAIS
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    private String codpais;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IIVS.LDAPPERU2.DESPAIS
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    private String despais;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IIVS.LDAPPERU2.CODEMP
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    private String codemp;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IIVS.LDAPPERU2.DESEMP
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    private String desemp;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IIVS.LDAPPERU2.NUMMAT
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    private String nummat;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IIVS.LDAPPERU2.NOMBRE
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    private String nombre;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IIVS.LDAPPERU2.APEPAT
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    private String apepat;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IIVS.LDAPPERU2.APEMAT
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    private String apemat;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IIVS.LDAPPERU2.SEXO
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    private String sexo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IIVS.LDAPPERU2.FECNAC
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    private String fecnac;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IIVS.LDAPPERU2.TIPDOC
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    private String tipdoc;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IIVS.LDAPPERU2.NUMDOC
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    private String numdoc;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IIVS.LDAPPERU2.TELEFONO1
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    private String telefono1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IIVS.LDAPPERU2.TELEFONO2
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    private String telefono2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IIVS.LDAPPERU2.CORELEC
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    private String corelec;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IIVS.LDAPPERU2.CODCARGO
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    private String codcargo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IIVS.LDAPPERU2.NOMCARGO
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    private String nomcargo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IIVS.LDAPPERU2.CODEMPANT
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    private String codempant;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IIVS.LDAPPERU2.CODOFI
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    private String codofi;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IIVS.LDAPPERU2.DESOFI
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    private String desofi;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IIVS.LDAPPERU2.TIPOFI
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    private String tipofi;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IIVS.LDAPPERU2.GESPER
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    private String gesper;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IIVS.LDAPPERU2.FECING
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    private String fecing;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IIVS.LDAPPERU2.NROHIJOS
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    private Short nrohijos;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IIVS.LDAPPERU2.CODGER
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    private String codger;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IIVS.LDAPPERU2.NOMGER
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    private String nomger;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IIVS.LDAPPERU2.TELOFI1
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    private String telofi1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IIVS.LDAPPERU2.TELOFI2
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    private String telofi2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IIVS.LDAPPERU2.CARBLAN
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    private String carblan;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IIVS.LDAPPERU2.PROINF
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    private String proinf;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IIVS.LDAPPERU2.CODUSUJEFE
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    private String codusujefe;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IIVS.LDAPPERU2.CODUNIORG
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    private String coduniorg;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IIVS.LDAPPERU2.DESUNIORG
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    private String desuniorg;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IIVS.LDAPPERU2.CODNIVEL1
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    private String codnivel1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IIVS.LDAPPERU2.DESNIVEL1
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    private String desnivel1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IIVS.LDAPPERU2.CODNIVEL2
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    private String codnivel2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IIVS.LDAPPERU2.DESNIVEL2
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    private String desnivel2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IIVS.LDAPPERU2.CODNIVEL3
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    private String codnivel3;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IIVS.LDAPPERU2.DESNIVEL3
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    private String desnivel3;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IIVS.LDAPPERU2.CODNIVEL4
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    private String codnivel4;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IIVS.LDAPPERU2.DESNIVEL4
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    private String desnivel4;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IIVS.LDAPPERU2.CODNIVEL5
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    private String codnivel5;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IIVS.LDAPPERU2.DESNIVEL5
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    private String desnivel5;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IIVS.LDAPPERU2.CODNIVEL6
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    private String codnivel6;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IIVS.LDAPPERU2.DESNIVEL6
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    private String desnivel6;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IIVS.LDAPPERU2.CODNIVEL7
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    private String codnivel7;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IIVS.LDAPPERU2.DESNIVEL7
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    private String desnivel7;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IIVS.LDAPPERU2.CODNIVEL8
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    private String codnivel8;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IIVS.LDAPPERU2.DESNIVEL8
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    private String desnivel8;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IIVS.LDAPPERU2.CODNIVEL9
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    private String codnivel9;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IIVS.LDAPPERU2.DESNIVEL9
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    private String desnivel9;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IIVS.LDAPPERU2.CODNIVEL10
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    private String codnivel10;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IIVS.LDAPPERU2.DESNIVEL10
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    private String desnivel10;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IIVS.LDAPPERU2.USOFUT1
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    private String usofut1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IIVS.LDAPPERU2.USOFUT2
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    private String usofut2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IIVS.LDAPPERU2.USOFUT3
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    private String usofut3;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IIVS.LDAPPERU2.USOFUT4
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    private String usofut4;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IIVS.LDAPPERU2.USOFUT5
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    private String usofut5;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IIVS.LDAPPERU2.USOFUT6
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    private String usofut6;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IIVS.LDAPPERU2.USOFUT7
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    private String usofut7;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IIVS.LDAPPERU2.USOFUT8
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    private String usofut8;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IIVS.LDAPPERU2.USOFUT9
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    private String usofut9;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column IIVS.LDAPPERU2.USOFUT10
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    private String usofut10;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IIVS.LDAPPERU2.CODUSU
     *
     * @return the value of IIVS.LDAPPERU2.CODUSU
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public String getCodusu() {
        return codusu;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IIVS.LDAPPERU2.CODUSU
     *
     * @param codusu the value for IIVS.LDAPPERU2.CODUSU
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public void setCodusu(String codusu) {
        this.codusu = codusu == null ? null : codusu.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IIVS.LDAPPERU2.REGISTROU
     *
     * @return the value of IIVS.LDAPPERU2.REGISTROU
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public String getRegistrou() {
        return registrou;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IIVS.LDAPPERU2.REGISTROU
     *
     * @param registrou the value for IIVS.LDAPPERU2.REGISTROU
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public void setRegistrou(String registrou) {
        this.registrou = registrou == null ? null : registrou.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IIVS.LDAPPERU2.REGISTROP
     *
     * @return the value of IIVS.LDAPPERU2.REGISTROP
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public String getRegistrop() {
        return registrop;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IIVS.LDAPPERU2.REGISTROP
     *
     * @param registrop the value for IIVS.LDAPPERU2.REGISTROP
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public void setRegistrop(String registrop) {
        this.registrop = registrop == null ? null : registrop.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IIVS.LDAPPERU2.CODPAIS
     *
     * @return the value of IIVS.LDAPPERU2.CODPAIS
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public String getCodpais() {
        return codpais;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IIVS.LDAPPERU2.CODPAIS
     *
     * @param codpais the value for IIVS.LDAPPERU2.CODPAIS
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public void setCodpais(String codpais) {
        this.codpais = codpais == null ? null : codpais.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IIVS.LDAPPERU2.DESPAIS
     *
     * @return the value of IIVS.LDAPPERU2.DESPAIS
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public String getDespais() {
        return despais;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IIVS.LDAPPERU2.DESPAIS
     *
     * @param despais the value for IIVS.LDAPPERU2.DESPAIS
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public void setDespais(String despais) {
        this.despais = despais == null ? null : despais.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IIVS.LDAPPERU2.CODEMP
     *
     * @return the value of IIVS.LDAPPERU2.CODEMP
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public String getCodemp() {
        return codemp;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IIVS.LDAPPERU2.CODEMP
     *
     * @param codemp the value for IIVS.LDAPPERU2.CODEMP
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public void setCodemp(String codemp) {
        this.codemp = codemp == null ? null : codemp.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IIVS.LDAPPERU2.DESEMP
     *
     * @return the value of IIVS.LDAPPERU2.DESEMP
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public String getDesemp() {
        return desemp;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IIVS.LDAPPERU2.DESEMP
     *
     * @param desemp the value for IIVS.LDAPPERU2.DESEMP
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public void setDesemp(String desemp) {
        this.desemp = desemp == null ? null : desemp.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IIVS.LDAPPERU2.NUMMAT
     *
     * @return the value of IIVS.LDAPPERU2.NUMMAT
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public String getNummat() {
        return nummat;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IIVS.LDAPPERU2.NUMMAT
     *
     * @param nummat the value for IIVS.LDAPPERU2.NUMMAT
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public void setNummat(String nummat) {
        this.nummat = nummat == null ? null : nummat.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IIVS.LDAPPERU2.NOMBRE
     *
     * @return the value of IIVS.LDAPPERU2.NOMBRE
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IIVS.LDAPPERU2.NOMBRE
     *
     * @param nombre the value for IIVS.LDAPPERU2.NOMBRE
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public void setNombre(String nombre) {
        this.nombre = nombre == null ? null : nombre.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IIVS.LDAPPERU2.APEPAT
     *
     * @return the value of IIVS.LDAPPERU2.APEPAT
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public String getApepat() {
        return apepat;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IIVS.LDAPPERU2.APEPAT
     *
     * @param apepat the value for IIVS.LDAPPERU2.APEPAT
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public void setApepat(String apepat) {
        this.apepat = apepat == null ? null : apepat.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IIVS.LDAPPERU2.APEMAT
     *
     * @return the value of IIVS.LDAPPERU2.APEMAT
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public String getApemat() {
        return apemat;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IIVS.LDAPPERU2.APEMAT
     *
     * @param apemat the value for IIVS.LDAPPERU2.APEMAT
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public void setApemat(String apemat) {
        this.apemat = apemat == null ? null : apemat.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IIVS.LDAPPERU2.SEXO
     *
     * @return the value of IIVS.LDAPPERU2.SEXO
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public String getSexo() {
        return sexo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IIVS.LDAPPERU2.SEXO
     *
     * @param sexo the value for IIVS.LDAPPERU2.SEXO
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public void setSexo(String sexo) {
        this.sexo = sexo == null ? null : sexo.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IIVS.LDAPPERU2.FECNAC
     *
     * @return the value of IIVS.LDAPPERU2.FECNAC
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public String getFecnac() {
        return fecnac;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IIVS.LDAPPERU2.FECNAC
     *
     * @param fecnac the value for IIVS.LDAPPERU2.FECNAC
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public void setFecnac(String fecnac) {
        this.fecnac = fecnac == null ? null : fecnac.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IIVS.LDAPPERU2.TIPDOC
     *
     * @return the value of IIVS.LDAPPERU2.TIPDOC
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public String getTipdoc() {
        return tipdoc;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IIVS.LDAPPERU2.TIPDOC
     *
     * @param tipdoc the value for IIVS.LDAPPERU2.TIPDOC
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public void setTipdoc(String tipdoc) {
        this.tipdoc = tipdoc == null ? null : tipdoc.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IIVS.LDAPPERU2.NUMDOC
     *
     * @return the value of IIVS.LDAPPERU2.NUMDOC
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public String getNumdoc() {
        return numdoc;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IIVS.LDAPPERU2.NUMDOC
     *
     * @param numdoc the value for IIVS.LDAPPERU2.NUMDOC
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public void setNumdoc(String numdoc) {
        this.numdoc = numdoc == null ? null : numdoc.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IIVS.LDAPPERU2.TELEFONO1
     *
     * @return the value of IIVS.LDAPPERU2.TELEFONO1
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public String getTelefono1() {
        return telefono1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IIVS.LDAPPERU2.TELEFONO1
     *
     * @param telefono1 the value for IIVS.LDAPPERU2.TELEFONO1
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public void setTelefono1(String telefono1) {
        this.telefono1 = telefono1 == null ? null : telefono1.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IIVS.LDAPPERU2.TELEFONO2
     *
     * @return the value of IIVS.LDAPPERU2.TELEFONO2
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public String getTelefono2() {
        return telefono2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IIVS.LDAPPERU2.TELEFONO2
     *
     * @param telefono2 the value for IIVS.LDAPPERU2.TELEFONO2
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public void setTelefono2(String telefono2) {
        this.telefono2 = telefono2 == null ? null : telefono2.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IIVS.LDAPPERU2.CORELEC
     *
     * @return the value of IIVS.LDAPPERU2.CORELEC
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public String getCorelec() {
        return corelec;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IIVS.LDAPPERU2.CORELEC
     *
     * @param corelec the value for IIVS.LDAPPERU2.CORELEC
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public void setCorelec(String corelec) {
        this.corelec = corelec == null ? null : corelec.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IIVS.LDAPPERU2.CODCARGO
     *
     * @return the value of IIVS.LDAPPERU2.CODCARGO
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public String getCodcargo() {
        return codcargo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IIVS.LDAPPERU2.CODCARGO
     *
     * @param codcargo the value for IIVS.LDAPPERU2.CODCARGO
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public void setCodcargo(String codcargo) {
        this.codcargo = codcargo == null ? null : codcargo.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IIVS.LDAPPERU2.NOMCARGO
     *
     * @return the value of IIVS.LDAPPERU2.NOMCARGO
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public String getNomcargo() {
        return nomcargo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IIVS.LDAPPERU2.NOMCARGO
     *
     * @param nomcargo the value for IIVS.LDAPPERU2.NOMCARGO
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public void setNomcargo(String nomcargo) {
        this.nomcargo = nomcargo == null ? null : nomcargo.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IIVS.LDAPPERU2.CODEMPANT
     *
     * @return the value of IIVS.LDAPPERU2.CODEMPANT
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public String getCodempant() {
        return codempant;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IIVS.LDAPPERU2.CODEMPANT
     *
     * @param codempant the value for IIVS.LDAPPERU2.CODEMPANT
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public void setCodempant(String codempant) {
        this.codempant = codempant == null ? null : codempant.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IIVS.LDAPPERU2.CODOFI
     *
     * @return the value of IIVS.LDAPPERU2.CODOFI
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public String getCodofi() {
        return codofi;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IIVS.LDAPPERU2.CODOFI
     *
     * @param codofi the value for IIVS.LDAPPERU2.CODOFI
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public void setCodofi(String codofi) {
        this.codofi = codofi == null ? null : codofi.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IIVS.LDAPPERU2.DESOFI
     *
     * @return the value of IIVS.LDAPPERU2.DESOFI
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public String getDesofi() {
        return desofi;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IIVS.LDAPPERU2.DESOFI
     *
     * @param desofi the value for IIVS.LDAPPERU2.DESOFI
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public void setDesofi(String desofi) {
        this.desofi = desofi == null ? null : desofi.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IIVS.LDAPPERU2.TIPOFI
     *
     * @return the value of IIVS.LDAPPERU2.TIPOFI
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public String getTipofi() {
        return tipofi;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IIVS.LDAPPERU2.TIPOFI
     *
     * @param tipofi the value for IIVS.LDAPPERU2.TIPOFI
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public void setTipofi(String tipofi) {
        this.tipofi = tipofi == null ? null : tipofi.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IIVS.LDAPPERU2.GESPER
     *
     * @return the value of IIVS.LDAPPERU2.GESPER
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public String getGesper() {
        return gesper;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IIVS.LDAPPERU2.GESPER
     *
     * @param gesper the value for IIVS.LDAPPERU2.GESPER
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public void setGesper(String gesper) {
        this.gesper = gesper == null ? null : gesper.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IIVS.LDAPPERU2.FECING
     *
     * @return the value of IIVS.LDAPPERU2.FECING
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public String getFecing() {
        return fecing;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IIVS.LDAPPERU2.FECING
     *
     * @param fecing the value for IIVS.LDAPPERU2.FECING
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public void setFecing(String fecing) {
        this.fecing = fecing == null ? null : fecing.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IIVS.LDAPPERU2.NROHIJOS
     *
     * @return the value of IIVS.LDAPPERU2.NROHIJOS
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public Short getNrohijos() {
        return nrohijos;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IIVS.LDAPPERU2.NROHIJOS
     *
     * @param nrohijos the value for IIVS.LDAPPERU2.NROHIJOS
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public void setNrohijos(Short nrohijos) {
        this.nrohijos = nrohijos;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IIVS.LDAPPERU2.CODGER
     *
     * @return the value of IIVS.LDAPPERU2.CODGER
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public String getCodger() {
        return codger;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IIVS.LDAPPERU2.CODGER
     *
     * @param codger the value for IIVS.LDAPPERU2.CODGER
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public void setCodger(String codger) {
        this.codger = codger == null ? null : codger.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IIVS.LDAPPERU2.NOMGER
     *
     * @return the value of IIVS.LDAPPERU2.NOMGER
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public String getNomger() {
        return nomger;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IIVS.LDAPPERU2.NOMGER
     *
     * @param nomger the value for IIVS.LDAPPERU2.NOMGER
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public void setNomger(String nomger) {
        this.nomger = nomger == null ? null : nomger.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IIVS.LDAPPERU2.TELOFI1
     *
     * @return the value of IIVS.LDAPPERU2.TELOFI1
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public String getTelofi1() {
        return telofi1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IIVS.LDAPPERU2.TELOFI1
     *
     * @param telofi1 the value for IIVS.LDAPPERU2.TELOFI1
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public void setTelofi1(String telofi1) {
        this.telofi1 = telofi1 == null ? null : telofi1.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IIVS.LDAPPERU2.TELOFI2
     *
     * @return the value of IIVS.LDAPPERU2.TELOFI2
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public String getTelofi2() {
        return telofi2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IIVS.LDAPPERU2.TELOFI2
     *
     * @param telofi2 the value for IIVS.LDAPPERU2.TELOFI2
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public void setTelofi2(String telofi2) {
        this.telofi2 = telofi2 == null ? null : telofi2.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IIVS.LDAPPERU2.CARBLAN
     *
     * @return the value of IIVS.LDAPPERU2.CARBLAN
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public String getCarblan() {
        return carblan;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IIVS.LDAPPERU2.CARBLAN
     *
     * @param carblan the value for IIVS.LDAPPERU2.CARBLAN
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public void setCarblan(String carblan) {
        this.carblan = carblan == null ? null : carblan.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IIVS.LDAPPERU2.PROINF
     *
     * @return the value of IIVS.LDAPPERU2.PROINF
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public String getProinf() {
        return proinf;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IIVS.LDAPPERU2.PROINF
     *
     * @param proinf the value for IIVS.LDAPPERU2.PROINF
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public void setProinf(String proinf) {
        this.proinf = proinf == null ? null : proinf.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IIVS.LDAPPERU2.CODUSUJEFE
     *
     * @return the value of IIVS.LDAPPERU2.CODUSUJEFE
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public String getCodusujefe() {
        return codusujefe;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IIVS.LDAPPERU2.CODUSUJEFE
     *
     * @param codusujefe the value for IIVS.LDAPPERU2.CODUSUJEFE
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public void setCodusujefe(String codusujefe) {
        this.codusujefe = codusujefe == null ? null : codusujefe.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IIVS.LDAPPERU2.CODUNIORG
     *
     * @return the value of IIVS.LDAPPERU2.CODUNIORG
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public String getCoduniorg() {
        return coduniorg;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IIVS.LDAPPERU2.CODUNIORG
     *
     * @param coduniorg the value for IIVS.LDAPPERU2.CODUNIORG
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public void setCoduniorg(String coduniorg) {
        this.coduniorg = coduniorg == null ? null : coduniorg.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IIVS.LDAPPERU2.DESUNIORG
     *
     * @return the value of IIVS.LDAPPERU2.DESUNIORG
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public String getDesuniorg() {
        return desuniorg;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IIVS.LDAPPERU2.DESUNIORG
     *
     * @param desuniorg the value for IIVS.LDAPPERU2.DESUNIORG
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public void setDesuniorg(String desuniorg) {
        this.desuniorg = desuniorg == null ? null : desuniorg.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IIVS.LDAPPERU2.CODNIVEL1
     *
     * @return the value of IIVS.LDAPPERU2.CODNIVEL1
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public String getCodnivel1() {
        return codnivel1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IIVS.LDAPPERU2.CODNIVEL1
     *
     * @param codnivel1 the value for IIVS.LDAPPERU2.CODNIVEL1
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public void setCodnivel1(String codnivel1) {
        this.codnivel1 = codnivel1 == null ? null : codnivel1.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IIVS.LDAPPERU2.DESNIVEL1
     *
     * @return the value of IIVS.LDAPPERU2.DESNIVEL1
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public String getDesnivel1() {
        return desnivel1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IIVS.LDAPPERU2.DESNIVEL1
     *
     * @param desnivel1 the value for IIVS.LDAPPERU2.DESNIVEL1
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public void setDesnivel1(String desnivel1) {
        this.desnivel1 = desnivel1 == null ? null : desnivel1.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IIVS.LDAPPERU2.CODNIVEL2
     *
     * @return the value of IIVS.LDAPPERU2.CODNIVEL2
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public String getCodnivel2() {
        return codnivel2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IIVS.LDAPPERU2.CODNIVEL2
     *
     * @param codnivel2 the value for IIVS.LDAPPERU2.CODNIVEL2
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public void setCodnivel2(String codnivel2) {
        this.codnivel2 = codnivel2 == null ? null : codnivel2.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IIVS.LDAPPERU2.DESNIVEL2
     *
     * @return the value of IIVS.LDAPPERU2.DESNIVEL2
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public String getDesnivel2() {
        return desnivel2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IIVS.LDAPPERU2.DESNIVEL2
     *
     * @param desnivel2 the value for IIVS.LDAPPERU2.DESNIVEL2
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public void setDesnivel2(String desnivel2) {
        this.desnivel2 = desnivel2 == null ? null : desnivel2.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IIVS.LDAPPERU2.CODNIVEL3
     *
     * @return the value of IIVS.LDAPPERU2.CODNIVEL3
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public String getCodnivel3() {
        return codnivel3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IIVS.LDAPPERU2.CODNIVEL3
     *
     * @param codnivel3 the value for IIVS.LDAPPERU2.CODNIVEL3
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public void setCodnivel3(String codnivel3) {
        this.codnivel3 = codnivel3 == null ? null : codnivel3.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IIVS.LDAPPERU2.DESNIVEL3
     *
     * @return the value of IIVS.LDAPPERU2.DESNIVEL3
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public String getDesnivel3() {
        return desnivel3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IIVS.LDAPPERU2.DESNIVEL3
     *
     * @param desnivel3 the value for IIVS.LDAPPERU2.DESNIVEL3
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public void setDesnivel3(String desnivel3) {
        this.desnivel3 = desnivel3 == null ? null : desnivel3.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IIVS.LDAPPERU2.CODNIVEL4
     *
     * @return the value of IIVS.LDAPPERU2.CODNIVEL4
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public String getCodnivel4() {
        return codnivel4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IIVS.LDAPPERU2.CODNIVEL4
     *
     * @param codnivel4 the value for IIVS.LDAPPERU2.CODNIVEL4
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public void setCodnivel4(String codnivel4) {
        this.codnivel4 = codnivel4 == null ? null : codnivel4.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IIVS.LDAPPERU2.DESNIVEL4
     *
     * @return the value of IIVS.LDAPPERU2.DESNIVEL4
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public String getDesnivel4() {
        return desnivel4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IIVS.LDAPPERU2.DESNIVEL4
     *
     * @param desnivel4 the value for IIVS.LDAPPERU2.DESNIVEL4
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public void setDesnivel4(String desnivel4) {
        this.desnivel4 = desnivel4 == null ? null : desnivel4.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IIVS.LDAPPERU2.CODNIVEL5
     *
     * @return the value of IIVS.LDAPPERU2.CODNIVEL5
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public String getCodnivel5() {
        return codnivel5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IIVS.LDAPPERU2.CODNIVEL5
     *
     * @param codnivel5 the value for IIVS.LDAPPERU2.CODNIVEL5
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public void setCodnivel5(String codnivel5) {
        this.codnivel5 = codnivel5 == null ? null : codnivel5.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IIVS.LDAPPERU2.DESNIVEL5
     *
     * @return the value of IIVS.LDAPPERU2.DESNIVEL5
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public String getDesnivel5() {
        return desnivel5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IIVS.LDAPPERU2.DESNIVEL5
     *
     * @param desnivel5 the value for IIVS.LDAPPERU2.DESNIVEL5
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public void setDesnivel5(String desnivel5) {
        this.desnivel5 = desnivel5 == null ? null : desnivel5.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IIVS.LDAPPERU2.CODNIVEL6
     *
     * @return the value of IIVS.LDAPPERU2.CODNIVEL6
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public String getCodnivel6() {
        return codnivel6;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IIVS.LDAPPERU2.CODNIVEL6
     *
     * @param codnivel6 the value for IIVS.LDAPPERU2.CODNIVEL6
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public void setCodnivel6(String codnivel6) {
        this.codnivel6 = codnivel6 == null ? null : codnivel6.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IIVS.LDAPPERU2.DESNIVEL6
     *
     * @return the value of IIVS.LDAPPERU2.DESNIVEL6
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public String getDesnivel6() {
        return desnivel6;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IIVS.LDAPPERU2.DESNIVEL6
     *
     * @param desnivel6 the value for IIVS.LDAPPERU2.DESNIVEL6
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public void setDesnivel6(String desnivel6) {
        this.desnivel6 = desnivel6 == null ? null : desnivel6.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IIVS.LDAPPERU2.CODNIVEL7
     *
     * @return the value of IIVS.LDAPPERU2.CODNIVEL7
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public String getCodnivel7() {
        return codnivel7;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IIVS.LDAPPERU2.CODNIVEL7
     *
     * @param codnivel7 the value for IIVS.LDAPPERU2.CODNIVEL7
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public void setCodnivel7(String codnivel7) {
        this.codnivel7 = codnivel7 == null ? null : codnivel7.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IIVS.LDAPPERU2.DESNIVEL7
     *
     * @return the value of IIVS.LDAPPERU2.DESNIVEL7
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public String getDesnivel7() {
        return desnivel7;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IIVS.LDAPPERU2.DESNIVEL7
     *
     * @param desnivel7 the value for IIVS.LDAPPERU2.DESNIVEL7
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public void setDesnivel7(String desnivel7) {
        this.desnivel7 = desnivel7 == null ? null : desnivel7.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IIVS.LDAPPERU2.CODNIVEL8
     *
     * @return the value of IIVS.LDAPPERU2.CODNIVEL8
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public String getCodnivel8() {
        return codnivel8;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IIVS.LDAPPERU2.CODNIVEL8
     *
     * @param codnivel8 the value for IIVS.LDAPPERU2.CODNIVEL8
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public void setCodnivel8(String codnivel8) {
        this.codnivel8 = codnivel8 == null ? null : codnivel8.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IIVS.LDAPPERU2.DESNIVEL8
     *
     * @return the value of IIVS.LDAPPERU2.DESNIVEL8
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public String getDesnivel8() {
        return desnivel8;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IIVS.LDAPPERU2.DESNIVEL8
     *
     * @param desnivel8 the value for IIVS.LDAPPERU2.DESNIVEL8
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public void setDesnivel8(String desnivel8) {
        this.desnivel8 = desnivel8 == null ? null : desnivel8.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IIVS.LDAPPERU2.CODNIVEL9
     *
     * @return the value of IIVS.LDAPPERU2.CODNIVEL9
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public String getCodnivel9() {
        return codnivel9;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IIVS.LDAPPERU2.CODNIVEL9
     *
     * @param codnivel9 the value for IIVS.LDAPPERU2.CODNIVEL9
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public void setCodnivel9(String codnivel9) {
        this.codnivel9 = codnivel9 == null ? null : codnivel9.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IIVS.LDAPPERU2.DESNIVEL9
     *
     * @return the value of IIVS.LDAPPERU2.DESNIVEL9
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public String getDesnivel9() {
        return desnivel9;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IIVS.LDAPPERU2.DESNIVEL9
     *
     * @param desnivel9 the value for IIVS.LDAPPERU2.DESNIVEL9
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public void setDesnivel9(String desnivel9) {
        this.desnivel9 = desnivel9 == null ? null : desnivel9.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IIVS.LDAPPERU2.CODNIVEL10
     *
     * @return the value of IIVS.LDAPPERU2.CODNIVEL10
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public String getCodnivel10() {
        return codnivel10;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IIVS.LDAPPERU2.CODNIVEL10
     *
     * @param codnivel10 the value for IIVS.LDAPPERU2.CODNIVEL10
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public void setCodnivel10(String codnivel10) {
        this.codnivel10 = codnivel10 == null ? null : codnivel10.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IIVS.LDAPPERU2.DESNIVEL10
     *
     * @return the value of IIVS.LDAPPERU2.DESNIVEL10
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public String getDesnivel10() {
        return desnivel10;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IIVS.LDAPPERU2.DESNIVEL10
     *
     * @param desnivel10 the value for IIVS.LDAPPERU2.DESNIVEL10
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public void setDesnivel10(String desnivel10) {
        this.desnivel10 = desnivel10 == null ? null : desnivel10.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IIVS.LDAPPERU2.USOFUT1
     *
     * @return the value of IIVS.LDAPPERU2.USOFUT1
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public String getUsofut1() {
        return usofut1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IIVS.LDAPPERU2.USOFUT1
     *
     * @param usofut1 the value for IIVS.LDAPPERU2.USOFUT1
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public void setUsofut1(String usofut1) {
        this.usofut1 = usofut1 == null ? null : usofut1.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IIVS.LDAPPERU2.USOFUT2
     *
     * @return the value of IIVS.LDAPPERU2.USOFUT2
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public String getUsofut2() {
        return usofut2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IIVS.LDAPPERU2.USOFUT2
     *
     * @param usofut2 the value for IIVS.LDAPPERU2.USOFUT2
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public void setUsofut2(String usofut2) {
        this.usofut2 = usofut2 == null ? null : usofut2.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IIVS.LDAPPERU2.USOFUT3
     *
     * @return the value of IIVS.LDAPPERU2.USOFUT3
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public String getUsofut3() {
        return usofut3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IIVS.LDAPPERU2.USOFUT3
     *
     * @param usofut3 the value for IIVS.LDAPPERU2.USOFUT3
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public void setUsofut3(String usofut3) {
        this.usofut3 = usofut3 == null ? null : usofut3.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IIVS.LDAPPERU2.USOFUT4
     *
     * @return the value of IIVS.LDAPPERU2.USOFUT4
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public String getUsofut4() {
        return usofut4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IIVS.LDAPPERU2.USOFUT4
     *
     * @param usofut4 the value for IIVS.LDAPPERU2.USOFUT4
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public void setUsofut4(String usofut4) {
        this.usofut4 = usofut4 == null ? null : usofut4.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IIVS.LDAPPERU2.USOFUT5
     *
     * @return the value of IIVS.LDAPPERU2.USOFUT5
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public String getUsofut5() {
        return usofut5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IIVS.LDAPPERU2.USOFUT5
     *
     * @param usofut5 the value for IIVS.LDAPPERU2.USOFUT5
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public void setUsofut5(String usofut5) {
        this.usofut5 = usofut5 == null ? null : usofut5.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IIVS.LDAPPERU2.USOFUT6
     *
     * @return the value of IIVS.LDAPPERU2.USOFUT6
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public String getUsofut6() {
        return usofut6;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IIVS.LDAPPERU2.USOFUT6
     *
     * @param usofut6 the value for IIVS.LDAPPERU2.USOFUT6
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public void setUsofut6(String usofut6) {
        this.usofut6 = usofut6 == null ? null : usofut6.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IIVS.LDAPPERU2.USOFUT7
     *
     * @return the value of IIVS.LDAPPERU2.USOFUT7
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public String getUsofut7() {
        return usofut7;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IIVS.LDAPPERU2.USOFUT7
     *
     * @param usofut7 the value for IIVS.LDAPPERU2.USOFUT7
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public void setUsofut7(String usofut7) {
        this.usofut7 = usofut7 == null ? null : usofut7.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IIVS.LDAPPERU2.USOFUT8
     *
     * @return the value of IIVS.LDAPPERU2.USOFUT8
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public String getUsofut8() {
        return usofut8;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IIVS.LDAPPERU2.USOFUT8
     *
     * @param usofut8 the value for IIVS.LDAPPERU2.USOFUT8
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public void setUsofut8(String usofut8) {
        this.usofut8 = usofut8 == null ? null : usofut8.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IIVS.LDAPPERU2.USOFUT9
     *
     * @return the value of IIVS.LDAPPERU2.USOFUT9
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public String getUsofut9() {
        return usofut9;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IIVS.LDAPPERU2.USOFUT9
     *
     * @param usofut9 the value for IIVS.LDAPPERU2.USOFUT9
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public void setUsofut9(String usofut9) {
        this.usofut9 = usofut9 == null ? null : usofut9.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column IIVS.LDAPPERU2.USOFUT10
     *
     * @return the value of IIVS.LDAPPERU2.USOFUT10
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public String getUsofut10() {
        return usofut10;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column IIVS.LDAPPERU2.USOFUT10
     *
     * @param usofut10 the value for IIVS.LDAPPERU2.USOFUT10
     *
     * @ibatorgenerated Mon Mar 22 14:37:03 COT 2010
     */
    public void setUsofut10(String usofut10) {
        this.usofut10 = usofut10 == null ? null : usofut10.trim();
    }
    /**
     * @return Returns the nombreCompleto.
     */
    public String getNombreCompleto() {
        return this.getNombre()+" "+ this.getApepat()+ " " + this.getApemat();
    }
    /**
     * @param nombreCompleto The nombreCompleto to set.
     */
    public void setNombreCompleto(String nombreCompleto) {
        this.nombreCompleto = nombreCompleto;
    }
}