/* TIPO DE REGISTRO */
UPDATE VISPOD.TIIVS_MULTITABLA SET VALOR1 = 'Titular', VALOR3 = 'R1' WHERE COD_MULT = 'T12' AND COD_ELEM = '0001';
UPDATE VISPOD.TIIVS_MULTITABLA SET VALOR1 = 'Apoderado', VALOR3 = 'R2' WHERE COD_MULT = 'T12' AND COD_ELEM = '0002';
INSERT INTO VISPOD.TIIVS_MULTITABLA (COD_MULT, COD_ELEM, VALOR1, VALOR2, VALOR3) VALUES ('T12', '0003', 'Heredero', '1', 'R2');

/* CLASIFICACION */
--TITULAR
UPDATE VISPOD.TIIVS_MULTITABLA SET VALOR1 = 'FALLECIDO', VALOR2 = '1', VALOR3 = '0001' WHERE COD_MULT = 'T13' AND COD_ELEM = '0001';
UPDATE VISPOD.TIIVS_MULTITABLA SET VALOR1 = 'MENOR DE EDAD', VALOR2 = '1', VALOR3 = '0001' WHERE COD_MULT = 'T13' AND COD_ELEM = '0002';
UPDATE VISPOD.TIIVS_MULTITABLA SET VALOR1 = 'INCAPAZ', VALOR2 = '1', VALOR3 = '0001' WHERE COD_MULT = 'T13' AND COD_ELEM = '0003';
UPDATE VISPOD.TIIVS_MULTITABLA SET VALOR1 = 'PERSONAS JURÍDICAS', VALOR2 = '1', VALOR3 = '0001' WHERE COD_MULT = 'T13' AND COD_ELEM = '0004';
UPDATE VISPOD.TIIVS_MULTITABLA SET VALOR1 = 'PERSONA NATURAL (+18 AÑOS)', VALOR2 = '1', VALOR3 = '0001' WHERE COD_MULT = 'T13' AND COD_ELEM = '0005';

-- APODERADO
UPDATE VISPOD.TIIVS_MULTITABLA SET VALOR1 = 'TUTOR', VALOR2 = '1', VALOR3 = '0002' WHERE COD_MULT = 'T13' AND COD_ELEM = '0006';
UPDATE VISPOD.TIIVS_MULTITABLA SET VALOR1 = 'CURADOR', VALOR2 = '1', VALOR3 = '0002' WHERE COD_MULT = 'T13' AND COD_ELEM = '0007';
UPDATE VISPOD.TIIVS_MULTITABLA SET VALOR1 = 'REPRESENTANTE', VALOR2 = '1', VALOR3 = '0002' WHERE COD_MULT = 'T13' AND COD_ELEM = '0008';

-- HEREDERO
UPDATE VISPOD.TIIVS_MULTITABLA SET VALOR1 = 'APODERADO', VALOR2 = '1', VALOR3 = '0003' WHERE COD_MULT = 'T13' AND COD_ELEM = '0009';
UPDATE VISPOD.TIIVS_MULTITABLA SET VALOR1 = 'DERECHO PROPIO', VALOR2 = '1', VALOR3 = '0003' WHERE COD_MULT = 'T13' AND COD_ELEM = '0010';

-- ELIMINACIÓN DE REGISTROS INACTIVOS
DELETE FROM VISPOD.TIIVS_MULTITABLA WHERE COD_MULT = 'T13' AND COD_ELEM = '0011';
DELETE FROM VISPOD.TIIVS_MULTITABLA WHERE COD_MULT = 'T13' AND COD_ELEM = '0012';


/* AGREGAR SCRIPT DE OPERACIONES BANCARIAS CON EL EXCEL DE PARAMETRIA */
ALTER TABLE VISPOD.TIIVS_SOLICITUD_OPERBAN DISABLE CONSTRAINT TIIVS_SOLICITUD_OPERBAN_T_FK2;
DELETE FROM VISPOD.TIIVS_OPERACION_BANCARIA;
ALTER TABLE VISPOD.tiivs_operacion_bancaria ADD TIPO VARCHAR2(50) NOT NULL;

Insert into VISPOD.TIIVS_OPERACION_BANCARIA (COD_OPER_BAN,DES_OPER_BAN,ACTIVO,TIPO) values ('0000001','RESCATE DE FONDOS MUTUOS','1','DINERARIA');
Insert into VISPOD.TIIVS_OPERACION_BANCARIA (COD_OPER_BAN,DES_OPER_BAN,ACTIVO,TIPO) values ('0000002','PAGO ELECTRÓNICO','1','DINERARIA');
Insert into VISPOD.TIIVS_OPERACION_BANCARIA (COD_OPER_BAN,DES_OPER_BAN,ACTIVO,TIPO) values ('0000003','SUBSIDIOS DE ESSALUD','1','DINERARIA');
Insert into VISPOD.TIIVS_OPERACION_BANCARIA (COD_OPER_BAN,DES_OPER_BAN,ACTIVO,TIPO) values ('0000004','REGISTRO EN EL SISTEMA DE APODERADOS','1','DINERARIA');
Insert into VISPOD.TIIVS_OPERACION_BANCARIA (COD_OPER_BAN,DES_OPER_BAN,ACTIVO,TIPO) values ('0000005','CREDITO HIPOTECARIO','1','DINERARIA');
Insert into VISPOD.TIIVS_OPERACION_BANCARIA (COD_OPER_BAN,DES_OPER_BAN,ACTIVO,TIPO) values ('0000006','SOCIEDAD NOFORMALIZADA (NO INSCRITA)','1','NO DINERARIA');
Insert into VISPOD.TIIVS_OPERACION_BANCARIA (COD_OPER_BAN,DES_OPER_BAN,ACTIVO,TIPO) values ('0000007','CAMBIO DE NOMBRE','1','NO DINERARIA');
Insert into VISPOD.TIIVS_OPERACION_BANCARIA (COD_OPER_BAN,DES_OPER_BAN,ACTIVO,TIPO) values ('0000008','INFORMACION DE DATOS PERSONALES LEY NRO 27933','1','NO DINERARIA');

COMMIT;

ALTER TABLE VISPOD.TIIVS_SOLICITUD_OPERBAN ENABLE CONSTRAINT TIIVS_SOLICITUD_OPERBAN_T_FK2;


/*** SEGUNDO ENTREGABLE ***/
-- AGREGAR UN NUEVO REGISTRE QUE IDENTIFIQUE LA VISIBILIDAD DEL CAMPO "EXONERA PAGO DE COMISION"
DELETE FROM VISPOD.TIIVS_MULTITABLA WHERE COD_MULT = 'T17';
INSERT INTO VISPOD.TIIVS_MULTITABLA (COD_MULT, COD_ELEM, VALOR1, VALOR2, VALOR3) VALUES ('T17', '0001', 'Exonerado de Pago de comisión', '1', 'Esta es una glosa');

-- SOLICITUD
ALTER TABLE VISPOD.TIIVS_SOLICITUD DROP COLUMN EXONERA_COMISION;
ALTER TABLE VISPOD.TIIVS_SOLICITUD ADD EXONERA_COMISION VARCHAR2(1);

