package com.hildebrando.visado.modelo;

// Generated 05/12/2012 11:41:39 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * HistorialdesolicitudId generated by hbm2java
 */
public class HistorialdesolicitudId implements java.io.Serializable {

	private BigDecimal rowId;
	private String codSoli;
	private String estado;

	public HistorialdesolicitudId() {
	}

	public HistorialdesolicitudId(String codSoli, String estado) {
		this.codSoli = codSoli;
		this.estado = estado;
	}

	public HistorialdesolicitudId(BigDecimal rowId, String codSoli,
			String estado) {
		this.rowId = rowId;
		this.codSoli = codSoli;
		this.estado = estado;
	}

	public BigDecimal getRowId() {
		return this.rowId;
	}

	public void setRowId(BigDecimal rowId) {
		this.rowId = rowId;
	}

	public String getCodSoli() {
		return this.codSoli;
	}

	public void setCodSoli(String codSoli) {
		this.codSoli = codSoli;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HistorialdesolicitudId))
			return false;
		HistorialdesolicitudId castOther = (HistorialdesolicitudId) other;

		return ((this.getRowId() == castOther.getRowId()) || (this.getRowId() != null
				&& castOther.getRowId() != null && this.getRowId().equals(
				castOther.getRowId())))
				&& ((this.getCodSoli() == castOther.getCodSoli()) || (this
						.getCodSoli() != null && castOther.getCodSoli() != null && this
						.getCodSoli().equals(castOther.getCodSoli())))
				&& ((this.getEstado() == castOther.getEstado()) || (this
						.getEstado() != null && castOther.getEstado() != null && this
						.getEstado().equals(castOther.getEstado())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getRowId() == null ? 0 : this.getRowId().hashCode());
		result = 37 * result
				+ (getCodSoli() == null ? 0 : this.getCodSoli().hashCode());
		result = 37 * result
				+ (getEstado() == null ? 0 : this.getEstado().hashCode());
		return result;
	}

}
