package com.hildebrando.visado.modelo;

// Generated 05/12/2012 11:17:13 AM by Hibernate Tools 3.4.0.CR1

/**
 * Historialdesolicitud generated by hbm2java
 */
public class Historialdesolicitud implements java.io.Serializable {

	private HistorialdesolicitudId id;

	public Historialdesolicitud() {
	}

	public Historialdesolicitud(HistorialdesolicitudId id) {
		this.id = id;
	}

	public HistorialdesolicitudId getId() {
		return this.id;
	}

	public void setId(HistorialdesolicitudId id) {
		this.id = id;
	}

}
