package com.hildebrando.visado.modelo;

// Generated 05/12/2012 06:03:07 PM by Hibernate Tools 3.4.0.CR1

/**
 * Ldapperu2 generated by hbm2java
 */
public class Ldapperu2 implements java.io.Serializable {

	private Ldapperu2Id id;

	public Ldapperu2() {
	}

	public Ldapperu2(Ldapperu2Id id) {
		this.id = id;
	}

	public Ldapperu2Id getId() {
		return this.id;
	}

	public void setId(Ldapperu2Id id) {
		this.id = id;
	}

}
