package com.hildebrando.visado.modelo;
// Generated 13-jun-2012 10:20:15 by Hibernate Tools 3.4.0.CR1



/**
 * QrtzPausedTriggerGrps generated by hbm2java
 */
public class QrtzPausedTriggerGrps  implements java.io.Serializable {


     private String triggerGroup;

    public QrtzPausedTriggerGrps() {
    }

    public QrtzPausedTriggerGrps(String triggerGroup) {
       this.triggerGroup = triggerGroup;
    }
   
    public String getTriggerGroup() {
        return this.triggerGroup;
    }
    
    public void setTriggerGroup(String triggerGroup) {
        this.triggerGroup = triggerGroup;
    }




}


