package com.hildebrando.visado.modelo;
// Generated 13-jun-2012 10:20:15 by Hibernate Tools 3.4.0.CR1



/**
 * QrtzTriggerListeners generated by hbm2java
 */
public class QrtzTriggerListeners  implements java.io.Serializable {


     private QrtzTriggerListenersId id;
     private QrtzTriggers qrtzTriggers;

    public QrtzTriggerListeners() {
    }

    public QrtzTriggerListeners(QrtzTriggerListenersId id, QrtzTriggers qrtzTriggers) {
       this.id = id;
       this.qrtzTriggers = qrtzTriggers;
    }
   
    public QrtzTriggerListenersId getId() {
        return this.id;
    }
    
    public void setId(QrtzTriggerListenersId id) {
        this.id = id;
    }
    public QrtzTriggers getQrtzTriggers() {
        return this.qrtzTriggers;
    }
    
    public void setQrtzTriggers(QrtzTriggers qrtzTriggers) {
        this.qrtzTriggers = qrtzTriggers;
    }




}


