package com.hildebrando.visado.modelo;
// Generated 13-jun-2012 10:20:15 by Hibernate Tools 3.4.0.CR1



/**
 * QrtzCronTriggersId generated by hbm2java
 */
public class QrtzCronTriggersId  implements java.io.Serializable {


     private String triggerName;
     private String triggerGroup;

    public QrtzCronTriggersId() {
    }

    public QrtzCronTriggersId(String triggerName, String triggerGroup) {
       this.triggerName = triggerName;
       this.triggerGroup = triggerGroup;
    }
   
    public String getTriggerName() {
        return this.triggerName;
    }
    
    public void setTriggerName(String triggerName) {
        this.triggerName = triggerName;
    }
    public String getTriggerGroup() {
        return this.triggerGroup;
    }
    
    public void setTriggerGroup(String triggerGroup) {
        this.triggerGroup = triggerGroup;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof QrtzCronTriggersId) ) return false;
		 QrtzCronTriggersId castOther = ( QrtzCronTriggersId ) other; 
         
		 return ( (this.getTriggerName()==castOther.getTriggerName()) || ( this.getTriggerName()!=null && castOther.getTriggerName()!=null && this.getTriggerName().equals(castOther.getTriggerName()) ) )
 && ( (this.getTriggerGroup()==castOther.getTriggerGroup()) || ( this.getTriggerGroup()!=null && castOther.getTriggerGroup()!=null && this.getTriggerGroup().equals(castOther.getTriggerGroup()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTriggerName() == null ? 0 : this.getTriggerName().hashCode() );
         result = 37 * result + ( getTriggerGroup() == null ? 0 : this.getTriggerGroup().hashCode() );
         return result;
   }   


}


