package com.hildebrando.visado.modelo;
// Generated 13-jun-2012 10:20:15 by Hibernate Tools 3.4.0.CR1



/**
 * QrtzTriggerListenersId generated by hbm2java
 */
public class QrtzTriggerListenersId  implements java.io.Serializable {


     private String triggerName;
     private String triggerGroup;
     private String triggerListener;

    public QrtzTriggerListenersId() {
    }

    public QrtzTriggerListenersId(String triggerName, String triggerGroup, String triggerListener) {
       this.triggerName = triggerName;
       this.triggerGroup = triggerGroup;
       this.triggerListener = triggerListener;
    }
   
    public String getTriggerName() {
        return this.triggerName;
    }
    
    public void setTriggerName(String triggerName) {
        this.triggerName = triggerName;
    }
    public String getTriggerGroup() {
        return this.triggerGroup;
    }
    
    public void setTriggerGroup(String triggerGroup) {
        this.triggerGroup = triggerGroup;
    }
    public String getTriggerListener() {
        return this.triggerListener;
    }
    
    public void setTriggerListener(String triggerListener) {
        this.triggerListener = triggerListener;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof QrtzTriggerListenersId) ) return false;
		 QrtzTriggerListenersId castOther = ( QrtzTriggerListenersId ) other; 
         
		 return ( (this.getTriggerName()==castOther.getTriggerName()) || ( this.getTriggerName()!=null && castOther.getTriggerName()!=null && this.getTriggerName().equals(castOther.getTriggerName()) ) )
 && ( (this.getTriggerGroup()==castOther.getTriggerGroup()) || ( this.getTriggerGroup()!=null && castOther.getTriggerGroup()!=null && this.getTriggerGroup().equals(castOther.getTriggerGroup()) ) )
 && ( (this.getTriggerListener()==castOther.getTriggerListener()) || ( this.getTriggerListener()!=null && castOther.getTriggerListener()!=null && this.getTriggerListener().equals(castOther.getTriggerListener()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTriggerName() == null ? 0 : this.getTriggerName().hashCode() );
         result = 37 * result + ( getTriggerGroup() == null ? 0 : this.getTriggerGroup().hashCode() );
         result = 37 * result + ( getTriggerListener() == null ? 0 : this.getTriggerListener().hashCode() );
         return result;
   }   


}


