package com.hildebrando.visado.modelo;
// Generated 13-jun-2012 10:20:15 by Hibernate Tools 3.4.0.CR1



/**
 * QrtzSimpleTriggers generated by hbm2java
 */
public class QrtzSimpleTriggers  implements java.io.Serializable {


	 private QrtzSimpleTriggersId id;
     private QrtzTriggers qrtzTriggers;
     private int repeatCount;
     private long repeatInterval;
     private int timesTriggered;

    public QrtzSimpleTriggers() {
    }

    public QrtzSimpleTriggers(QrtzTriggers qrtzTriggers, int repeatCount, long repeatInterval, int timesTriggered) {
       this.qrtzTriggers = qrtzTriggers;
       this.repeatCount = repeatCount;
       this.repeatInterval = repeatInterval;
       this.timesTriggered = timesTriggered;
    }
   
    public QrtzSimpleTriggersId getId() {
        return this.id;
    }
    
    public void setId(QrtzSimpleTriggersId id) {
        this.id = id;
    }
    public QrtzTriggers getQrtzTriggers() {
        return this.qrtzTriggers;
    }
    
    public void setQrtzTriggers(QrtzTriggers qrtzTriggers) {
        this.qrtzTriggers = qrtzTriggers;
    }
    public int getRepeatCount() {
        return this.repeatCount;
    }
    
    public void setRepeatCount(int repeatCount) {
        this.repeatCount = repeatCount;
    }
    public long getRepeatInterval() {
        return this.repeatInterval;
    }
    
    public void setRepeatInterval(long repeatInterval) {
        this.repeatInterval = repeatInterval;
    }
    public int getTimesTriggered() {
        return this.timesTriggered;
    }
    
    public void setTimesTriggered(int timesTriggered) {
        this.timesTriggered = timesTriggered;
    }




}


