package com.hildebrando.visado.modelo;
// Generated 13-jun-2012 10:20:15 by Hibernate Tools 3.4.0.CR1



/**
 * QrtzCronTriggers generated by hbm2java
 */
public class QrtzCronTriggers  implements java.io.Serializable {


     private QrtzCronTriggersId id;
     private QrtzTriggers qrtzTriggers;
     private String cronExpression;
     private String timeZoneId;

    public QrtzCronTriggers() {
    }

	
    public QrtzCronTriggers(QrtzTriggers qrtzTriggers, String cronExpression) {
        this.qrtzTriggers = qrtzTriggers;
        this.cronExpression = cronExpression;
    }
    public QrtzCronTriggers(QrtzTriggers qrtzTriggers, String cronExpression, String timeZoneId) {
       this.qrtzTriggers = qrtzTriggers;
       this.cronExpression = cronExpression;
       this.timeZoneId = timeZoneId;
    }
   
    public QrtzCronTriggersId getId() {
        return this.id;
    }
    
    public void setId(QrtzCronTriggersId id) {
        this.id = id;
    }
    public QrtzTriggers getQrtzTriggers() {
        return this.qrtzTriggers;
    }
    
    public void setQrtzTriggers(QrtzTriggers qrtzTriggers) {
        this.qrtzTriggers = qrtzTriggers;
    }
    public String getCronExpression() {
        return this.cronExpression;
    }
    
    public void setCronExpression(String cronExpression) {
        this.cronExpression = cronExpression;
    }
    public String getTimeZoneId() {
        return this.timeZoneId;
    }
    
    public void setTimeZoneId(String timeZoneId) {
        this.timeZoneId = timeZoneId;
    }




}


