package com.hildebrando.visado.modelo;
// Generated 13-jun-2012 10:20:15 by Hibernate Tools 3.4.0.CR1


import java.sql.Blob;

/**
 * QrtzBlobTriggers generated by hbm2java
 */
public class QrtzBlobTriggers  implements java.io.Serializable {
 
	 private static final long serialVersionUID = 1L;
	 private QrtzBlobTriggersId id;
     private QrtzTriggers qrtzTriggers;
     private Blob blobData;

    public QrtzBlobTriggers() {
    }

	
    public QrtzBlobTriggers(QrtzTriggers qrtzTriggers) {
        this.qrtzTriggers = qrtzTriggers;
    }
    public QrtzBlobTriggers(QrtzTriggers qrtzTriggers, Blob blobData) {
       this.qrtzTriggers = qrtzTriggers;
       this.blobData = blobData;
    }
   
    public QrtzBlobTriggersId getId() {
        return this.id;
    }
    
    public void setId(QrtzBlobTriggersId id) {
        this.id = id;
    }
    public QrtzTriggers getQrtzTriggers() {
        return this.qrtzTriggers;
    }
    
    public void setQrtzTriggers(QrtzTriggers qrtzTriggers) {
        this.qrtzTriggers = qrtzTriggers;
    }
    public Blob getBlobData() {
        return this.blobData;
    }
    
    public void setBlobData(Blob blobData) {
        this.blobData = blobData;
    }




}


