package com.hildebrando.visado.modelo;
// Generated 13-jun-2012 10:20:15 by Hibernate Tools 3.4.0.CR1


import java.sql.Blob;

/**
 * QrtzCalendars generated by hbm2java
 */
public class QrtzCalendars  implements java.io.Serializable {


     private String calendarName;
     private Blob calendar;

    public QrtzCalendars() {
    }

    public QrtzCalendars(String calendarName, Blob calendar) {
       this.calendarName = calendarName;
       this.calendar = calendar;
    }
   
    public String getCalendarName() {
        return this.calendarName;
    }
    
    public void setCalendarName(String calendarName) {
        this.calendarName = calendarName;
    }
    public Blob getCalendar() {
        return this.calendar;
    }
    
    public void setCalendar(Blob calendar) {
        this.calendar = calendar;
    }




}


