package com.hildebrando.visado.modelo;

// Generated 05/12/2012 11:17:13 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * TiivsSolicitudOperban generated by hbm2java
 */
public class TiivsSolicitudOperban implements java.io.Serializable {

	private TiivsSolicitudOperbanId id;
	private TiivsOperacionBancaria tiivsOperacionBancaria;
	private BigDecimal importe;
	private String moneda;
	private BigDecimal tipoCambio;

	public TiivsSolicitudOperban() {
	}

	public TiivsSolicitudOperban(TiivsSolicitudOperbanId id,
			TiivsOperacionBancaria tiivsOperacionBancaria) {
		this.id = id;
		this.tiivsOperacionBancaria = tiivsOperacionBancaria;
	}

	public TiivsSolicitudOperban(TiivsSolicitudOperbanId id,
			TiivsOperacionBancaria tiivsOperacionBancaria, BigDecimal importe,
			String moneda, BigDecimal tipoCambio) {
		this.id = id;
		this.tiivsOperacionBancaria = tiivsOperacionBancaria;
		this.importe = importe;
		this.moneda = moneda;
		this.tipoCambio = tipoCambio;
	}

	public TiivsSolicitudOperbanId getId() {
		return this.id;
	}

	public void setId(TiivsSolicitudOperbanId id) {
		this.id = id;
	}

	public TiivsOperacionBancaria getTiivsOperacionBancaria() {
		return this.tiivsOperacionBancaria;
	}

	public void setTiivsOperacionBancaria(
			TiivsOperacionBancaria tiivsOperacionBancaria) {
		this.tiivsOperacionBancaria = tiivsOperacionBancaria;
	}

	public BigDecimal getImporte() {
		return this.importe;
	}

	public void setImporte(BigDecimal importe) {
		this.importe = importe;
	}

	public String getMoneda() {
		return this.moneda;
	}

	public void setMoneda(String moneda) {
		this.moneda = moneda;
	}

	public BigDecimal getTipoCambio() {
		return this.tipoCambio;
	}

	public void setTipoCambio(BigDecimal tipoCambio) {
		this.tipoCambio = tipoCambio;
	}

}
