package com.hildebrando.visado.modelo;

// Generated 07/11/2012 02:39:40 PM by Hibernate Tools 3.4.0.CR1

/**
 * TiivsTareaGrupo generated by hbm2java
 */
public class TiivsTareaGrupo implements java.io.Serializable {

	private TiivsTareaGrupoId id;
	private TiivsGrupo tiivsGrupo;
	private TiivsTarea tiivsTarea;

	public TiivsTareaGrupo() {
	}

	public TiivsTareaGrupo(TiivsTareaGrupoId id, TiivsGrupo tiivsGrupo,
			TiivsTarea tiivsTarea) {
		this.id = id;
		this.tiivsGrupo = tiivsGrupo;
		this.tiivsTarea = tiivsTarea;
	}

	public TiivsTareaGrupoId getId() {
		return this.id;
	}

	public void setId(TiivsTareaGrupoId id) {
		this.id = id;
	}

	public TiivsGrupo getTiivsGrupo() {
		return this.tiivsGrupo;
	}

	public void setTiivsGrupo(TiivsGrupo tiivsGrupo) {
		this.tiivsGrupo = tiivsGrupo;
	}

	public TiivsTarea getTiivsTarea() {
		return this.tiivsTarea;
	}

	public void setTiivsTarea(TiivsTarea tiivsTarea) {
		this.tiivsTarea = tiivsTarea;
	}

}
