package com.hildebrando.visado.modelo;

// Generated 07/11/2012 02:39:40 PM by Hibernate Tools 3.4.0.CR1

/**
 * TiivsAnexoSolicitud generated by hbm2java
 */
public class TiivsAnexoSolicitud implements java.io.Serializable {

	private TiivsAnexoSolicitudId id;
	private TiivsTipoDocumento tiivsTipoDocumento;
	private String aliasArchivo;

	public TiivsAnexoSolicitud() {
	}

	public TiivsAnexoSolicitud(TiivsAnexoSolicitudId id,
			TiivsTipoDocumento tiivsTipoDocumento, String aliasArchivo) {
		this.id = id;
		this.tiivsTipoDocumento = tiivsTipoDocumento;
		this.aliasArchivo = aliasArchivo;
	}

	public TiivsAnexoSolicitudId getId() {
		return this.id;
	}

	public void setId(TiivsAnexoSolicitudId id) {
		this.id = id;
	}

	public TiivsTipoDocumento getTiivsTipoDocumento() {
		return this.tiivsTipoDocumento;
	}

	public void setTiivsTipoDocumento(TiivsTipoDocumento tiivsTipoDocumento) {
		this.tiivsTipoDocumento = tiivsTipoDocumento;
	}

	public String getAliasArchivo() {
		return this.aliasArchivo;
	}

	public void setAliasArchivo(String aliasArchivo) {
		this.aliasArchivo = aliasArchivo;
	}

}
