package com.hildebrando.visado.modelo;

// Generated 10/01/2013 11:57:43 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TiivsDocumento generated by hbm2java
 */
public class TiivsDocumento implements java.io.Serializable {

	private String codDocumento;
	private String descripcion;
	private String activo;
	private String nombre;
	private String formato;
	private String codBarra;
	private Set<TiivsTipoSolicDocumento> tiivsTipoSolicDocumentos = new HashSet<TiivsTipoSolicDocumento>();

	public TiivsDocumento() {
	}

	public TiivsDocumento(String codDocumento) {
		this.codDocumento = codDocumento;
	}

	public TiivsDocumento(String codDocumento, String descripcion,
			String activo, Set tiivsTipoSolicDocumentos) {
		this.codDocumento = codDocumento;
		this.descripcion = descripcion;
		this.activo = activo;
		this.tiivsTipoSolicDocumentos = tiivsTipoSolicDocumentos;
	}

	public String getCodDocumento() {
		return this.codDocumento;
	}

	public void setCodDocumento(String codDocumento) {
		this.codDocumento = codDocumento;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getActivo() {
		return this.activo;
	}

	public void setActivo(String activo) {
		this.activo = activo;
	}
	
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getFormato() {
		return this.formato;
	}

	public void setFormato(String formato) {
		this.formato = formato;
	}		

	public String getCodBarra() {
		return codBarra;
	}

	public void setCodBarra(String codBarra) {
		this.codBarra = codBarra;
	}

	public Set getTiivsTipoSolicDocumentos() {
		return this.tiivsTipoSolicDocumentos;
	}

	public void setTiivsTipoSolicDocumentos(Set tiivsTipoSolicDocumentos) {
		this.tiivsTipoSolicDocumentos = tiivsTipoSolicDocumentos;
	}

}
