package com.hildebrando.visado.modelo;

// Generated 07/11/2012 02:39:40 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TiivsTipoServicio generated by hbm2java
 */
public class TiivsTipoServicio implements java.io.Serializable {

	private String codOper;
	private String desOper;
	private char activo;
	private Set tiivsTipoDocumentos = new HashSet(0);
	private Set tiivsSolicituds = new HashSet(0);

	public TiivsTipoServicio() {
	}

	public TiivsTipoServicio(String codOper, String desOper, char activo) {
		this.codOper = codOper;
		this.desOper = desOper;
		this.activo = activo;
	}

	public TiivsTipoServicio(String codOper, String desOper, char activo,
			Set tiivsTipoDocumentos, Set tiivsSolicituds) {
		this.codOper = codOper;
		this.desOper = desOper;
		this.activo = activo;
		this.tiivsTipoDocumentos = tiivsTipoDocumentos;
		this.tiivsSolicituds = tiivsSolicituds;
	}

	public String getCodOper() {
		return this.codOper;
	}

	public void setCodOper(String codOper) {
		this.codOper = codOper;
	}

	public String getDesOper() {
		return this.desOper;
	}

	public void setDesOper(String desOper) {
		this.desOper = desOper;
	}

	public char getActivo() {
		return this.activo;
	}

	public void setActivo(char activo) {
		this.activo = activo;
	}

	public Set getTiivsTipoDocumentos() {
		return this.tiivsTipoDocumentos;
	}

	public void setTiivsTipoDocumentos(Set tiivsTipoDocumentos) {
		this.tiivsTipoDocumentos = tiivsTipoDocumentos;
	}

	public Set getTiivsSolicituds() {
		return this.tiivsSolicituds;
	}

	public void setTiivsSolicituds(Set tiivsSolicituds) {
		this.tiivsSolicituds = tiivsSolicituds;
	}

}
