package com.hildebrando.visado.modelo;

// Generated 05/12/2012 11:41:39 AM by Hibernate 
/**
 * TiivsSolicitudOperban generated by hbm2java
 */
public class TiivsSolicitudOperban implements java.io.Serializable {
    private String sItem;
	private TiivsSolicitudOperbanId id;
	private TiivsOperacionBancaria tiivsOperacionBancaria;
	private double importe;
	private String moneda;
	private double tipoCambio;
	private double importeSoles;

	public TiivsSolicitudOperban() {
	}

	public TiivsSolicitudOperban(TiivsSolicitudOperbanId id,
			TiivsOperacionBancaria tiivsOperacionBancaria) {
		this.id = id;
		this.tiivsOperacionBancaria = tiivsOperacionBancaria;
	}

	public TiivsSolicitudOperban(TiivsSolicitudOperbanId id,
			TiivsOperacionBancaria tiivsOperacionBancaria, double importe,
			String moneda, double tipoCambio) {
		this.id = id;
		this.tiivsOperacionBancaria = tiivsOperacionBancaria;
		this.importe = importe;
		this.moneda = moneda;
		this.tipoCambio = tipoCambio;
	}

	public TiivsSolicitudOperbanId getId() {
		return this.id;
	}

	public void setId(TiivsSolicitudOperbanId id) {
		this.id = id;
	}

	public TiivsOperacionBancaria getTiivsOperacionBancaria() {
		return this.tiivsOperacionBancaria;
	}

	public void setTiivsOperacionBancaria(
			TiivsOperacionBancaria tiivsOperacionBancaria) {
		this.tiivsOperacionBancaria = tiivsOperacionBancaria;
	}

	public double getImporte() {
		return this.importe;
	}

	public void setImporte(double importe) {
		this.importe = importe;
	}

	public String getMoneda() {
		return this.moneda;
	}

	public void setMoneda(String moneda) {
		this.moneda = moneda;
	}

	public double getTipoCambio() {
		return this.tipoCambio;
	}

	public void setTipoCambio(double tipoCambio) {
		this.tipoCambio = tipoCambio;
	}

	public double getImporteSoles() {
		return importeSoles;
	}

	public void setImporteSoles(double importeSoles) {
		this.importeSoles = importeSoles;
	}

	public String getsItem() {
		return sItem;
	}

	public void setsItem(String sItem) {
		this.sItem = sItem;
	}

}
