package com.hildebrando.visado.modelo;

// Generated 05/12/2012 11:41:39 AM by Hibernate Tools 3.4.0.CR1

/**
 * TiivsSolicitudEstadoNivel generated by hbm2java
 */
public class TiivsSolicitudEstadoNivel implements java.io.Serializable {

	private TiivsSolicitudEstadoNivelId id;

	public TiivsSolicitudEstadoNivel() {
	}

	public TiivsSolicitudEstadoNivel(TiivsSolicitudEstadoNivelId id) {
		this.id = id;
	}

	public TiivsSolicitudEstadoNivelId getId() {
		return this.id;
	}

	public void setId(TiivsSolicitudEstadoNivelId id) {
		this.id = id;
	}

}
