package com.hildebrando.visado.modelo;

// Generated 05/12/2012 11:41:39 AM by Hibernate Tools 3.4.0.CR1

/**
 * TiivsSolicitudEstadoNivelId generated by hbm2java
 */
public class TiivsSolicitudEstadoNivelId implements java.io.Serializable {

	private String codSol;
	private String codNivel;
	private String codEstado;
	private String codUsuario;
	private String tipo;

	public TiivsSolicitudEstadoNivelId() {
	}

	public TiivsSolicitudEstadoNivelId(String codSol, String codNivel,
			String codEstado, String codUsuario, String tipo) {
		this.codSol = codSol;
		this.codNivel = codNivel;
		this.codEstado = codEstado;
		this.codUsuario = codUsuario;
		this.tipo = tipo;
	}

	public String getCodSol() {
		return this.codSol;
	}

	public void setCodSol(String codSol) {
		this.codSol = codSol;
	}

	public String getCodNivel() {
		return this.codNivel;
	}

	public void setCodNivel(String codNivel) {
		this.codNivel = codNivel;
	}

	public String getCodEstado() {
		return this.codEstado;
	}

	public void setCodEstado(String codEstado) {
		this.codEstado = codEstado;
	}

	public String getCodUsuario() {
		return this.codUsuario;
	}

	public void setCodUsuario(String codUsuario) {
		this.codUsuario = codUsuario;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TiivsSolicitudEstadoNivelId))
			return false;
		TiivsSolicitudEstadoNivelId castOther = (TiivsSolicitudEstadoNivelId) other;

		return ((this.getCodSol() == castOther.getCodSol()) || (this
				.getCodSol() != null && castOther.getCodSol() != null && this
				.getCodSol().equals(castOther.getCodSol())))
				&& ((this.getCodNivel() == castOther.getCodNivel()) || (this
						.getCodNivel() != null
						&& castOther.getCodNivel() != null && this
						.getCodNivel().equals(castOther.getCodNivel())))
				&& ((this.getCodEstado() == castOther.getCodEstado()) || (this
						.getCodEstado() != null
						&& castOther.getCodEstado() != null && this
						.getCodEstado().equals(castOther.getCodEstado())))
				&& ((this.getCodUsuario() == castOther.getCodUsuario()) || (this
						.getCodUsuario() != null
						&& castOther.getCodUsuario() != null && this
						.getCodUsuario().equals(castOther.getCodUsuario())))
				&& ((this.getTipo() == castOther.getTipo()) || (this.getTipo() != null
						&& castOther.getTipo() != null && this.getTipo()
						.equals(castOther.getTipo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCodSol() == null ? 0 : this.getCodSol().hashCode());
		result = 37 * result
				+ (getCodNivel() == null ? 0 : this.getCodNivel().hashCode());
		result = 37 * result
				+ (getCodEstado() == null ? 0 : this.getCodEstado().hashCode());
		result = 37
				* result
				+ (getCodUsuario() == null ? 0 : this.getCodUsuario()
						.hashCode());
		result = 37 * result
				+ (getTipo() == null ? 0 : this.getTipo().hashCode());
		return result;
	}

}
