package com.hildebrando.visado.modelo;

// Generated 12/12/2012 12:08:20 PM by Hibernate Tools 3.4.0.CR
import java.sql.Timestamp;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TiivsSolicitud generated by hbm2java
 */
public class TiivsSolicitud implements java.io.Serializable {

	private String codSoli;
	private TiivsEstudio tiivsEstudio;
	private TiivsTipoSolicitud tiivsTipoSolicitud;
	private TiivsOficina1 tiivsOficina1;
	private String estado;
    private String descEstado;
	private Date fecha;
	private String regAbogado;
	private String obs;
	private String regUsuario;
	private String nomUsuario;
	private Double importe;
	private Timestamp fechaEnvio;
	private Timestamp fechaEstado;
	private String moneda;
    private String sImporteMoneda;  
	private Timestamp fechaRespuesta;
// MODIFICACION 
	private Double comision;
	private String nroVoucher;
	private Set tiivsSolicitudNivels = new HashSet(0);
	private Set<TiivsSolicitudAgrupacion> tiivsSolicitudAgrupacions = new HashSet<TiivsSolicitudAgrupacion>();
	private String txtEstado;
	private String txtImporte;
	private String txtApoderado;
	private String txtPoderdante;
	private String txtOpeBan;
	private String txtNivel;

	public TiivsSolicitud() {
	}

	public TiivsSolicitud(String codSoli,
			TiivsTipoSolicitud tiivsTipoSolicitud, TiivsOficina1 tiivsOficina1,
			String estado, Timestamp fecha, String regUsuario,
			String nomUsuario) {
		this.codSoli = codSoli;
		this.tiivsTipoSolicitud = tiivsTipoSolicitud;
		this.tiivsOficina1 = tiivsOficina1;
		this.estado = estado;
		this.fecha = fecha;
		this.regUsuario = regUsuario;
		this.nomUsuario = nomUsuario;
	}

	public TiivsSolicitud(String codSoli, TiivsEstudio tiivsEstudio,
			TiivsTipoSolicitud tiivsTipoSolicitud, TiivsOficina1 tiivsOficina1,
			String estado, Timestamp fecha, String regAbogado, String obs,
			String regUsuario, String nomUsuario, Double importe,
			Timestamp fechaEnvio, Timestamp fechaEstado, String moneda,
			Timestamp fechaRespuesta, Double comision,
			String nroVoucher, Set tiivsSolicitudNivels,
			Set tiivsSolicitudAgrupacions) {
		this.codSoli = codSoli;
		this.tiivsEstudio = tiivsEstudio;
		this.tiivsTipoSolicitud = tiivsTipoSolicitud;
		this.tiivsOficina1 = tiivsOficina1;
		this.estado = estado;
		this.fecha = fecha;
		this.regAbogado = regAbogado;
		this.obs = obs;
		this.regUsuario = regUsuario;
		this.nomUsuario = nomUsuario;
		this.importe = importe;
		this.fechaEnvio = fechaEnvio;
		this.fechaEstado = fechaEstado;
		this.moneda = moneda;
		this.fechaRespuesta = fechaRespuesta;
		this.comision = comision;
		this.nroVoucher = nroVoucher;
		this.tiivsSolicitudNivels = tiivsSolicitudNivels;
		this.tiivsSolicitudAgrupacions = tiivsSolicitudAgrupacions;
	}

	public String getCodSoli() {
		return this.codSoli;
	}

	public void setCodSoli(String codSoli) {
		this.codSoli = codSoli;
	}

	public TiivsEstudio getTiivsEstudio() {
		return this.tiivsEstudio;
	}

	public void setTiivsEstudio(TiivsEstudio tiivsEstudio) {
		this.tiivsEstudio = tiivsEstudio;
	}

	public TiivsTipoSolicitud getTiivsTipoSolicitud() {
		return this.tiivsTipoSolicitud;
	}

	public void setTiivsTipoSolicitud(TiivsTipoSolicitud tiivsTipoSolicitud) {
		this.tiivsTipoSolicitud = tiivsTipoSolicitud;
	}

	public TiivsOficina1 getTiivsOficina1() {
		return this.tiivsOficina1;
	}

	public void setTiivsOficina1(TiivsOficina1 tiivsOficina1) {
		this.tiivsOficina1 = tiivsOficina1;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}


	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {

		this.fecha = fecha;
	}

	public String getRegAbogado() {
		return this.regAbogado;
	}

	public void setRegAbogado(String regAbogado) {
		this.regAbogado = regAbogado;
	}

	public String getObs() {
		return this.obs;
	}

	public void setObs(String obs) {
		this.obs = obs;
	}

	public String getRegUsuario() {
		return this.regUsuario;
	}

	public void setRegUsuario(String regUsuario) {
		this.regUsuario = regUsuario;
	}

	public String getNomUsuario() {
		return this.nomUsuario;
	}

	public void setNomUsuario(String nomUsuario) {
		this.nomUsuario = nomUsuario;
	}

	public Double getImporte() {
		return this.importe;
	}

	public void setImporte(Double importe) {
		this.importe = importe;
	}


	public Timestamp getFechaEnvio() {
		return this.fechaEnvio;
	}

	public void setFechaEnvio(Timestamp fechaEnvio) {
		this.fechaEnvio = fechaEnvio;
	}

	public Timestamp getFechaEstado() {
		return this.fechaEstado;
	}

	public void setFechaEstado(Timestamp fechaEstado) {
		this.fechaEstado = fechaEstado;
	}

	public String getMoneda() {
		return this.moneda;
	}

	public void setMoneda(String moneda) {
		this.moneda = moneda;
	}


	public Timestamp getFechaRespuesta() {
		return this.fechaRespuesta;
	}

	public void setFechaRespuesta(Timestamp fechaRespuesta) {
		this.fechaRespuesta = fechaRespuesta;
	}

	public Double getComision() {
		return this.comision;
	}

	public void setComision(Double comision) {
		this.comision = comision;
	}

	public String getNroVoucher() {
		return this.nroVoucher;
	}

	public void setNroVoucher(String nroVoucher) {
		this.nroVoucher = nroVoucher;
	}

	public Set getTiivsSolicitudNivels() {
		return this.tiivsSolicitudNivels;
	}

	public void setTiivsSolicitudNivels(Set tiivsSolicitudNivels) {
		this.tiivsSolicitudNivels = tiivsSolicitudNivels;
	}

	
	public Set<TiivsSolicitudAgrupacion> getTiivsSolicitudAgrupacions() {
		return tiivsSolicitudAgrupacions;
	}

	public void setTiivsSolicitudAgrupacions(
			Set<TiivsSolicitudAgrupacion> tiivsSolicitudAgrupacions) {
		this.tiivsSolicitudAgrupacions = tiivsSolicitudAgrupacions;
	}

	public String getDescEstado() {
		return descEstado;
	}

	public void setDescEstado(String descEstado) {
		this.descEstado = descEstado;
	}

	public String getsImporteMoneda() {
		return sImporteMoneda;
	}

	public void setsImporteMoneda(String sImporteMoneda) {
		this.sImporteMoneda = sImporteMoneda;
	}

	public String getTxtEstado() {
		return txtEstado;
	}

	public void setTxtEstado(String txtEstado) {
		this.txtEstado = txtEstado;
	}

	public String getTxtImporte() {
		return txtImporte;
	}

	public void setTxtImporte(String txtImporte) {
		this.txtImporte = txtImporte;
	}

	public String getTxtApoderado() {
		return txtApoderado;
	}

	public void setTxtApoderado(String txtApoderado) {
		this.txtApoderado = txtApoderado;
	}

	public String getTxtPoderdante() {
		return txtPoderdante;
	}

	public void setTxtPoderdante(String txtPoderdante) {
		this.txtPoderdante = txtPoderdante;
	}

	public String getTxtOpeBan() {
		return txtOpeBan;
	}

	public void setTxtOpeBan(String txtOpeBan) {
		this.txtOpeBan = txtOpeBan;
	}

	public String getTxtNivel() {
		return txtNivel;
	}

	public void setTxtNivel(String txtNivel) {
		this.txtNivel = txtNivel;
	}
}
