package com.hildebrando.visado.modelo;

// Generated 10/01/2013 11:57:43 AM by Hibernate Tools 3.4.0.CR1

/**
 * TiivsTipoSolicDocumentoId generated by hbm2java
 */
public class TiivsTipoSolicDocumentoId implements java.io.Serializable {

	private String codTipoSolic;
	private String codDoc;

	public TiivsTipoSolicDocumentoId() {
	}

	public TiivsTipoSolicDocumentoId(String codTipoSolic, String codDoc) {
		this.codTipoSolic = codTipoSolic;
		this.codDoc = codDoc;
	}

	public String getCodTipoSolic() {
		return this.codTipoSolic;
	}

	public void setCodTipoSolic(String codTipoSolic) {
		this.codTipoSolic = codTipoSolic;
	}

	public String getCodDoc() {
		return this.codDoc;
	}

	public void setCodDoc(String codDoc) {
		this.codDoc = codDoc;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TiivsTipoSolicDocumentoId))
			return false;
		TiivsTipoSolicDocumentoId castOther = (TiivsTipoSolicDocumentoId) other;

		return ((this.getCodTipoSolic() == castOther.getCodTipoSolic()) || (this
				.getCodTipoSolic() != null
				&& castOther.getCodTipoSolic() != null && this
				.getCodTipoSolic().equals(castOther.getCodTipoSolic())))
				&& ((this.getCodDoc() == castOther.getCodDoc()) || (this
						.getCodDoc() != null && castOther.getCodDoc() != null && this
						.getCodDoc().equals(castOther.getCodDoc())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCodTipoSolic() == null ? 0 : this.getCodTipoSolic()
						.hashCode());
		result = 37 * result
				+ (getCodDoc() == null ? 0 : this.getCodDoc().hashCode());
		return result;
	}

}
