package com.hildebrando.visado.modelo;

// Generated Feb 20, 2013 12:11:27 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * TiivsNivel generated by hbm2java
 */
public class TiivsNivel implements java.io.Serializable {

	private int id;
	private String codNiv;
	private String desNiv;
	private Integer rangoInicio;
	private Integer rangoFin;
	private String moneda;
	private Date fechaReg;
	private String usuarioReg;
	private Date fechaAct;
	private String usuarioAct;
	private BigDecimal estado;

	public TiivsNivel() {
	}

	public TiivsNivel(int id) {
		this.id = id;
	}

	public TiivsNivel(int id, String codNiv, String desNiv,
			Integer rangoInicio, Integer rangoFin, String moneda,
			Date fechaReg, String usuarioReg, Date fechaAct, String usuarioAct,
			BigDecimal estado) {
		this.id = id;
		this.codNiv = codNiv;
		this.desNiv = desNiv;
		this.rangoInicio = rangoInicio;
		this.rangoFin = rangoFin;
		this.moneda = moneda;
		this.fechaReg = fechaReg;
		this.usuarioReg = usuarioReg;
		this.fechaAct = fechaAct;
		this.usuarioAct = usuarioAct;
		this.estado = estado;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getCodNiv() {
		return this.codNiv;
	}

	public void setCodNiv(String codNiv) {
		this.codNiv = codNiv;
	}

	public String getDesNiv() {
		return this.desNiv;
	}

	public void setDesNiv(String desNiv) {
		this.desNiv = desNiv;
	}

	public Integer getRangoInicio() {
		return this.rangoInicio;
	}

	public void setRangoInicio(Integer rangoInicio) {
		this.rangoInicio = rangoInicio;
	}

	public Integer getRangoFin() {
		return this.rangoFin;
	}

	public void setRangoFin(Integer rangoFin) {
		this.rangoFin = rangoFin;
	}

	public String getMoneda() {
		return this.moneda;
	}

	public void setMoneda(String moneda) {
		this.moneda = moneda;
	}

	public Date getFechaReg() {
		return this.fechaReg;
	}

	public void setFechaReg(Date fechaReg) {
		this.fechaReg = fechaReg;
	}

	public String getUsuarioReg() {
		return this.usuarioReg;
	}

	public void setUsuarioReg(String usuarioReg) {
		this.usuarioReg = usuarioReg;
	}

	public Date getFechaAct() {
		return this.fechaAct;
	}

	public void setFechaAct(Date fechaAct) {
		this.fechaAct = fechaAct;
	}

	public String getUsuarioAct() {
		return this.usuarioAct;
	}

	public void setUsuarioAct(String usuarioAct) {
		this.usuarioAct = usuarioAct;
	}

	public BigDecimal getEstado() {
		return this.estado;
	}

	public void setEstado(BigDecimal estado) {
		this.estado = estado;
	}

}
