package com.hildebrando.visado.modelo;

// Generated 07/11/2012 02:39:40 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TiivsGrupo generated by hbm2java
 */
public class TiivsGrupo implements java.io.Serializable {

	private String codGrupo;
	private String desGrupo;
	private Set tiivsTareaGrupos = new HashSet(0);
	private Set tiivsMiembros = new HashSet(0);

	public TiivsGrupo() {
	}

	public TiivsGrupo(String codGrupo, String desGrupo) {
		this.codGrupo = codGrupo;
		this.desGrupo = desGrupo;
	}

	public TiivsGrupo(String codGrupo, String desGrupo, Set tiivsTareaGrupos,
			Set tiivsMiembros) {
		this.codGrupo = codGrupo;
		this.desGrupo = desGrupo;
		this.tiivsTareaGrupos = tiivsTareaGrupos;
		this.tiivsMiembros = tiivsMiembros;
	}

	public String getCodGrupo() {
		return this.codGrupo;
	}

	public void setCodGrupo(String codGrupo) {
		this.codGrupo = codGrupo;
	}

	public String getDesGrupo() {
		return this.desGrupo;
	}

	public void setDesGrupo(String desGrupo) {
		this.desGrupo = desGrupo;
	}

	public Set getTiivsTareaGrupos() {
		return this.tiivsTareaGrupos;
	}

	public void setTiivsTareaGrupos(Set tiivsTareaGrupos) {
		this.tiivsTareaGrupos = tiivsTareaGrupos;
	}

	public Set getTiivsMiembros() {
		return this.tiivsMiembros;
	}

	public void setTiivsMiembros(Set tiivsMiembros) {
		this.tiivsMiembros = tiivsMiembros;
	}

}
