package com.hildebrando.visado.modelo;

// Generated 07/11/2012 02:39:40 PM by Hibernate Tools 3.4.0.CR1

/**
 * TiivsOficina generated by hbm2java
 */
public class TiivsOficina implements java.io.Serializable {

	private String codOfi;
	private TiivsTerritorio tiivsTerritorio;
	private String desOfi;

	public TiivsOficina() {
	}

	public TiivsOficina(String codOfi, TiivsTerritorio tiivsTerritorio,
			String desOfi) {
		this.codOfi = codOfi;
		this.tiivsTerritorio = tiivsTerritorio;
		this.desOfi = desOfi;
	}

	public String getCodOfi() {
		return this.codOfi;
	}

	public void setCodOfi(String codOfi) {
		this.codOfi = codOfi;
	}

	public TiivsTerritorio getTiivsTerritorio() {
		return this.tiivsTerritorio;
	}

	public void setTiivsTerritorio(TiivsTerritorio tiivsTerritorio) {
		this.tiivsTerritorio = tiivsTerritorio;
	}

	public String getDesOfi() {
		return this.desOfi;
	}

	public void setDesOfi(String desOfi) {
		this.desOfi = desOfi;
	}

}
