package com.hildebrando.visado.modelo;

// Generated Feb 6, 2013 3:28:58 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TiivsRevocado generated by hbm2java
 */
public class TiivsRevocado implements java.io.Serializable {

	private int codRevocado;
	private TiivsPersona tiivsPersonaByCodPerApoderado;
	private TiivsPersona tiivsPersonaByCodPerPoderdante;
	private Character estado;
	private Date fechaRevocatoria;
	private Integer codAgrup;

	public TiivsRevocado() {
	}

	public TiivsRevocado(int codRevocado) {
		this.codRevocado = codRevocado;
	}

	public TiivsRevocado(int codRevocado,
			TiivsPersona tiivsPersonaByCodPerApoderado,
			TiivsPersona tiivsPersonaByCodPerPoderdante, Character estado,
			Date fechaRevocatoria, Integer codAgrup) {
		this.codRevocado = codRevocado;
		this.tiivsPersonaByCodPerApoderado = tiivsPersonaByCodPerApoderado;
		this.tiivsPersonaByCodPerPoderdante = tiivsPersonaByCodPerPoderdante;
		this.estado = estado;
		this.fechaRevocatoria = fechaRevocatoria;
		this.codAgrup = codAgrup;
	}

	public int getCodRevocado() {
		return this.codRevocado;
	}

	public void setCodRevocado(int codRevocado) {
		this.codRevocado = codRevocado;
	}

	public TiivsPersona getTiivsPersonaByCodPerApoderado() {
		return this.tiivsPersonaByCodPerApoderado;
	}

	public void setTiivsPersonaByCodPerApoderado(
			TiivsPersona tiivsPersonaByCodPerApoderado) {
		this.tiivsPersonaByCodPerApoderado = tiivsPersonaByCodPerApoderado;
	}

	public TiivsPersona getTiivsPersonaByCodPerPoderdante() {
		return this.tiivsPersonaByCodPerPoderdante;
	}

	public void setTiivsPersonaByCodPerPoderdante(
			TiivsPersona tiivsPersonaByCodPerPoderdante) {
		this.tiivsPersonaByCodPerPoderdante = tiivsPersonaByCodPerPoderdante;
	}

	public Character getEstado() {
		return this.estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}

	public Date getFechaRevocatoria() {
		return this.fechaRevocatoria;
	}

	public void setFechaRevocatoria(Date fechaRevocatoria) {
		this.fechaRevocatoria = fechaRevocatoria;
	}

	public Integer getCodAgrup() {
		return this.codAgrup;
	}

	public void setCodAgrup(Integer codAgrup) {
		this.codAgrup = codAgrup;
	}

}
