package com.hildebrando.visado.modelo;

// Generated 05/12/2012 02:50:20 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TiivsSolicitudAgrupacion generated by hbm2java
 */
public class TiivsSolicitudAgrupacion implements java.io.Serializable {

	private TiivsSolicitudAgrupacionId id;
	private TiivsSolicitud tiivsSolicitud;
	private String estado;
	private Set<TiivsAgrupacionPersona> tiivsAgrupacionPersonas = new HashSet<TiivsAgrupacionPersona>();

	public TiivsSolicitudAgrupacion() {
	}

	public TiivsSolicitudAgrupacion(TiivsSolicitudAgrupacionId id,
			TiivsSolicitud tiivsSolicitud) {
		this.id = id;
		this.tiivsSolicitud = tiivsSolicitud;
	}

	public TiivsSolicitudAgrupacion(TiivsSolicitudAgrupacionId id,
			TiivsSolicitud tiivsSolicitud, String activo,
			Set tiivsAgrupacionPersonas) {
		this.id = id;
		this.tiivsSolicitud = tiivsSolicitud;
		this.estado = activo;
		this.tiivsAgrupacionPersonas = tiivsAgrupacionPersonas;
	}

	public TiivsSolicitudAgrupacionId getId() {
		return this.id;
	}

	public void setId(TiivsSolicitudAgrupacionId id) {
		this.id = id;
	}

	public TiivsSolicitud getTiivsSolicitud() {
		return this.tiivsSolicitud;
	}

	public void setTiivsSolicitud(TiivsSolicitud tiivsSolicitud) {
		this.tiivsSolicitud = tiivsSolicitud;
	}

	public Set<TiivsAgrupacionPersona> getTiivsAgrupacionPersonas() {
		return tiivsAgrupacionPersonas;
	}

	public void setTiivsAgrupacionPersonas(
			Set<TiivsAgrupacionPersona> tiivsAgrupacionPersonas) {
		this.tiivsAgrupacionPersonas = tiivsAgrupacionPersonas;
	}

	public String getEstado() {
		return estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}


}
