package com.hildebrando.visado.modelo;

// Generated 10/12/2012 04:37:45 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * TiivsSolicitud generated by hbm2java
 */
public class TiivsSolicitud implements java.io.Serializable {

	private String codSoli;
	private TiivsEstudio tiivsEstudio;
	private TiivsTipoSolicitud tiivsTipoSolicitud;
	private TiivsOficina1 tiivsOficina1;
	private String estado;
	private Timestamp fecha;
	private String regAbogado;
	private String obs;
	private String regUsuario;
	private String nomUsuario;
	private BigDecimal importe;
	private Timestamp fechaEnvio;
	private Timestamp fechaEstado;
	private String moneda;
	private Timestamp fechaRespuesta;
	private BigDecimal comision;
	private String nroVoucher;
	private Set tiivsSolicitudAgrupacions = new HashSet(0);

	public TiivsSolicitud() {
	}

	public TiivsSolicitud(String codSoli,
			TiivsTipoSolicitud tiivsTipoSolicitud, TiivsOficina1 tiivsOficina1,
			String estado, Timestamp fecha, String regUsuario,
			String nomUsuario) {
		this.codSoli = codSoli;
		this.tiivsTipoSolicitud = tiivsTipoSolicitud;
		this.tiivsOficina1 = tiivsOficina1;
		this.estado = estado;
		this.fecha = fecha;
		this.regUsuario = regUsuario;
		this.nomUsuario = nomUsuario;
	}

	public TiivsSolicitud(String codSoli, TiivsEstudio tiivsEstudio,
			TiivsTipoSolicitud tiivsTipoSolicitud, TiivsOficina1 tiivsOficina1,
			String estado, Timestamp fecha, String regAbogado, String obs,
			String regUsuario, String nomUsuario, BigDecimal importe,
			Timestamp fechaEnvio, Timestamp fechaEstado, String moneda,
			Timestamp fechaRespuesta, BigDecimal comision,
			String nroVoucher, Set tiivsSolicitudAgrupacions) {
		this.codSoli = codSoli;
		this.tiivsEstudio = tiivsEstudio;
		this.tiivsTipoSolicitud = tiivsTipoSolicitud;
		this.tiivsOficina1 = tiivsOficina1;
		this.estado = estado;
		this.fecha = fecha;
		this.regAbogado = regAbogado;
		this.obs = obs;
		this.regUsuario = regUsuario;
		this.nomUsuario = nomUsuario;
		this.importe = importe;
		this.fechaEnvio = fechaEnvio;
		this.fechaEstado = fechaEstado;
		this.moneda = moneda;
		this.fechaRespuesta = fechaRespuesta;
		this.comision = comision;
		this.nroVoucher = nroVoucher;
		this.tiivsSolicitudAgrupacions = tiivsSolicitudAgrupacions;
	}

	public String getCodSoli() {
		return this.codSoli;
	}

	public void setCodSoli(String codSoli) {
		this.codSoli = codSoli;
	}

	public TiivsEstudio getTiivsEstudio() {
		return this.tiivsEstudio;
	}

	public void setTiivsEstudio(TiivsEstudio tiivsEstudio) {
		this.tiivsEstudio = tiivsEstudio;
	}

	public TiivsTipoSolicitud getTiivsTipoSolicitud() {
		return this.tiivsTipoSolicitud;
	}

	public void setTiivsTipoSolicitud(TiivsTipoSolicitud tiivsTipoSolicitud) {
		this.tiivsTipoSolicitud = tiivsTipoSolicitud;
	}

	public TiivsOficina1 getTiivsOficina1() {
		return this.tiivsOficina1;
	}

	public void setTiivsOficina1(TiivsOficina1 tiivsOficina1) {
		this.tiivsOficina1 = tiivsOficina1;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Serializable getFecha() {
		return this.fecha;
	}

	public void setFecha(Timestamp fecha) {
		this.fecha = fecha;
	}

	public String getRegAbogado() {
		return this.regAbogado;
	}

	public void setRegAbogado(String regAbogado) {
		this.regAbogado = regAbogado;
	}

	public String getObs() {
		return this.obs;
	}

	public void setObs(String obs) {
		this.obs = obs;
	}

	public String getRegUsuario() {
		return this.regUsuario;
	}

	public void setRegUsuario(String regUsuario) {
		this.regUsuario = regUsuario;
	}

	public String getNomUsuario() {
		return this.nomUsuario;
	}

	public void setNomUsuario(String nomUsuario) {
		this.nomUsuario = nomUsuario;
	}

	public BigDecimal getImporte() {
		return this.importe;
	}

	public void setImporte(BigDecimal importe) {
		this.importe = importe;
	}

	public Serializable getFechaEnvio() {
		return this.fechaEnvio;
	}

	public void setFechaEnvio(Timestamp fechaEnvio) {
		this.fechaEnvio = fechaEnvio;
	}

	public Serializable getFechaEstado() {
		return this.fechaEstado;
	}

	public void setFechaEstado(Timestamp fechaEstado) {
		this.fechaEstado = fechaEstado;
	}

	public String getMoneda() {
		return this.moneda;
	}

	public void setMoneda(String moneda) {
		this.moneda = moneda;
	}

	public Serializable getFechaRespuesta() {
		return this.fechaRespuesta;
	}

	public void setFechaRespuesta(Timestamp fechaRespuesta) {
		this.fechaRespuesta = fechaRespuesta;
	}

	public BigDecimal getComision() {
		return this.comision;
	}

	public void setComision(BigDecimal comision) {
		this.comision = comision;
	}

	public String getNroVoucher() {
		return this.nroVoucher;
	}

	public void setNroVoucher(String nroVoucher) {
		this.nroVoucher = nroVoucher;
	}

	public Set getTiivsSolicitudAgrupacions() {
		return this.tiivsSolicitudAgrupacions;
	}

	public void setTiivsSolicitudAgrupacions(Set tiivsSolicitudAgrupacions) {
		this.tiivsSolicitudAgrupacions = tiivsSolicitudAgrupacions;
	}

}
