package com.hildebrando.visado.modelo;

// Generated 05/12/2012 11:41:39 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TiivsTipoSolicDocumento generated by hbm2java
 */
public class TiivsTipoSolicDocumento implements java.io.Serializable {

	private String codDoc;
	private TiivsTipoSolicitud tiivsTipoSolicitud;
	private String desDoc;
	private char activo;
	private char obligatorio;

	public TiivsTipoSolicDocumento() {
	}

	public TiivsTipoSolicDocumento(String codDoc,
			TiivsTipoSolicitud tiivsTipoSolicitud, String desDoc, char activo,
			char obligatorio) {
		this.codDoc = codDoc;
		this.tiivsTipoSolicitud = tiivsTipoSolicitud;
		this.desDoc = desDoc;
		this.activo = activo;
		this.obligatorio = obligatorio;
	}

	public String getCodDoc() {
		return this.codDoc;
	}

	public void setCodDoc(String codDoc) {
		this.codDoc = codDoc;
	}

	public TiivsTipoSolicitud getTiivsTipoSolicitud() {
		return this.tiivsTipoSolicitud;
	}

	public void setTiivsTipoSolicitud(TiivsTipoSolicitud tiivsTipoSolicitud) {
		this.tiivsTipoSolicitud = tiivsTipoSolicitud;
	}

	public String getDesDoc() {
		return this.desDoc;
	}

	public void setDesDoc(String desDoc) {
		this.desDoc = desDoc;
	}

	public char getActivo() {
		return this.activo;
	}

	public void setActivo(char activo) {
		this.activo = activo;
	}

	public char getObligatorio() {
		return this.obligatorio;
	}

	public void setObligatorio(char obligatorio) {
		this.obligatorio = obligatorio;
	}
	
	public boolean equals(Object object){
		boolean ret = (object instanceof TiivsTipoSolicDocumento) && (codDoc != null) 
	             ? codDoc.equals(((TiivsTipoSolicDocumento) object).codDoc) 
	             : (object == this);
		return ret;
	}

}
