package com.hildebrando.visado.modelo;

// Generated 12/12/2012 12:08:20 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * TiivsSolicitudNivel generated by hbm2java
 */
public class TiivsSolicitudNivel implements java.io.Serializable {

	private TiivsSolicitudNivelId id;
	private TiivsSolicitud tiivsSolicitud;
	private String estado;
	private String usuarioRegistro;
	private Timestamp fechaRegistro;
	private Set tiivsMovimientoNivels = new HashSet(0);

	public TiivsSolicitudNivel() {
	}

	public TiivsSolicitudNivel(TiivsSolicitudNivelId id,
			TiivsSolicitud tiivsSolicitud) {
		this.id = id;
		this.tiivsSolicitud = tiivsSolicitud;
	}

	public TiivsSolicitudNivel(TiivsSolicitudNivelId id,
			TiivsSolicitud tiivsSolicitud, String estado,
			String usuarioRegistro, Timestamp fechaRegistro,
			Set tiivsMovimientoNivels) {
		this.id = id;
		this.tiivsSolicitud = tiivsSolicitud;
		this.estado = estado;
		this.usuarioRegistro = usuarioRegistro;
		this.fechaRegistro = fechaRegistro;
		this.tiivsMovimientoNivels = tiivsMovimientoNivels;
	}

	public TiivsSolicitudNivelId getId() {
		return this.id;
	}

	public void setId(TiivsSolicitudNivelId id) {
		this.id = id;
	}

	public TiivsSolicitud getTiivsSolicitud() {
		return this.tiivsSolicitud;
	}

	public void setTiivsSolicitud(TiivsSolicitud tiivsSolicitud) {
		this.tiivsSolicitud = tiivsSolicitud;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getUsuarioRegistro() {
		return this.usuarioRegistro;
	}

	public void setUsuarioRegistro(String usuarioRegistro) {
		this.usuarioRegistro = usuarioRegistro;
	}

	public Serializable getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Timestamp fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	public Set getTiivsMovimientoNivels() {
		return this.tiivsMovimientoNivels;
	}

	public void setTiivsMovimientoNivels(Set tiivsMovimientoNivels) {
		this.tiivsMovimientoNivels = tiivsMovimientoNivels;
	}

}
