package com.hildebrando.visado.modelo;

// Generated 05/12/2012 11:17:13 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * TiivsAgrupacionPersonaId generated by hbm2java
 */
public class TiivsAgrupacionPersonaId implements java.io.Serializable {

	private String codSoli;
	private BigDecimal codAgrup;
	private BigDecimal codPer;
	private BigDecimal tipPartic;
	private String clasifPer;

	public TiivsAgrupacionPersonaId() {
	}

	public TiivsAgrupacionPersonaId(String codSoli, BigDecimal codAgrup,
			BigDecimal codPer, BigDecimal tipPartic, String clasifPer) {
		this.codSoli = codSoli;
		this.codAgrup = codAgrup;
		this.codPer = codPer;
		this.tipPartic = tipPartic;
		this.clasifPer = clasifPer;
	}

	public String getCodSoli() {
		return this.codSoli;
	}

	public void setCodSoli(String codSoli) {
		this.codSoli = codSoli;
	}

	public BigDecimal getCodAgrup() {
		return this.codAgrup;
	}

	public void setCodAgrup(BigDecimal codAgrup) {
		this.codAgrup = codAgrup;
	}

	public BigDecimal getCodPer() {
		return this.codPer;
	}

	public void setCodPer(BigDecimal codPer) {
		this.codPer = codPer;
	}

	public BigDecimal getTipPartic() {
		return this.tipPartic;
	}

	public void setTipPartic(BigDecimal tipPartic) {
		this.tipPartic = tipPartic;
	}

	public String getClasifPer() {
		return this.clasifPer;
	}

	public void setClasifPer(String clasifPer) {
		this.clasifPer = clasifPer;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TiivsAgrupacionPersonaId))
			return false;
		TiivsAgrupacionPersonaId castOther = (TiivsAgrupacionPersonaId) other;

		return ((this.getCodSoli() == castOther.getCodSoli()) || (this
				.getCodSoli() != null && castOther.getCodSoli() != null && this
				.getCodSoli().equals(castOther.getCodSoli())))
				&& ((this.getCodAgrup() == castOther.getCodAgrup()) || (this
						.getCodAgrup() != null
						&& castOther.getCodAgrup() != null && this
						.getCodAgrup().equals(castOther.getCodAgrup())))
				&& ((this.getCodPer() == castOther.getCodPer()) || (this
						.getCodPer() != null && castOther.getCodPer() != null && this
						.getCodPer().equals(castOther.getCodPer())))
				&& ((this.getTipPartic() == castOther.getTipPartic()) || (this
						.getTipPartic() != null
						&& castOther.getTipPartic() != null && this
						.getTipPartic().equals(castOther.getTipPartic())))
				&& ((this.getClasifPer() == castOther.getClasifPer()) || (this
						.getClasifPer() != null
						&& castOther.getClasifPer() != null && this
						.getClasifPer().equals(castOther.getClasifPer())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCodSoli() == null ? 0 : this.getCodSoli().hashCode());
		result = 37 * result
				+ (getCodAgrup() == null ? 0 : this.getCodAgrup().hashCode());
		result = 37 * result
				+ (getCodPer() == null ? 0 : this.getCodPer().hashCode());
		result = 37 * result
				+ (getTipPartic() == null ? 0 : this.getTipPartic().hashCode());
		result = 37 * result
				+ (getClasifPer() == null ? 0 : this.getClasifPer().hashCode());
		return result;
	}

}
