package com.hildebrando.visado.modelo;

// Generated 07/11/2012 02:39:40 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TiivsOficina1 generated by hbm2java
 */
public class TiivsOficina1 implements java.io.Serializable {

	private String codOfi;
	private String desOfi;
	private Character activo;
	private String codTerr;
	private Set tiivsSolicituds = new HashSet(0);

	public TiivsOficina1() {
	}

	public TiivsOficina1(String codOfi) {
		this.codOfi = codOfi;
	}

	public TiivsOficina1(String codOfi, String desOfi, Character activo,
			String codTerr, Set tiivsSolicituds) {
		this.codOfi = codOfi;
		this.desOfi = desOfi;
		this.activo = activo;
		this.codTerr = codTerr;
		this.tiivsSolicituds = tiivsSolicituds;
	}

	public String getCodOfi() {
		return this.codOfi;
	}

	public void setCodOfi(String codOfi) {
		this.codOfi = codOfi;
	}

	public String getDesOfi() {
		return this.desOfi;
	}

	public void setDesOfi(String desOfi) {
		this.desOfi = desOfi;
	}

	public Character getActivo() {
		return this.activo;
	}

	public void setActivo(Character activo) {
		this.activo = activo;
	}

	public String getCodTerr() {
		return this.codTerr;
	}

	public void setCodTerr(String codTerr) {
		this.codTerr = codTerr;
	}

	public Set getTiivsSolicituds() {
		return this.tiivsSolicituds;
	}

	public void setTiivsSolicituds(Set tiivsSolicituds) {
		this.tiivsSolicituds = tiivsSolicituds;
	}

}
