package com.hildebrando.visado.modelo;

// Generated Feb 5, 2013 7:15:49 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TiivsRevocado generated by hbm2java
 */
public class TiivsRevocado implements java.io.Serializable {

	private int codRevocado;
	private TiivsPersona tiivsPersonaByCodPer2;
	private TiivsPersona tiivsPersonaByCodPer1;
	private String codMultPer1;
	private String codMultPer2;
	private Character estado;
	private Date fechaRevocatoria;
	private Integer codAgrup;

	public TiivsRevocado() {
	}

	public TiivsRevocado(int codRevocado) {
		this.codRevocado = codRevocado;
	}

	public TiivsRevocado(int codRevocado, TiivsPersona tiivsPersonaByCodPer2,
			TiivsPersona tiivsPersonaByCodPer1, String codMultPer1,
			String codMultPer2, Character estado, Date fechaRevocatoria,
			Integer codAgrup) {
		this.codRevocado = codRevocado;
		this.tiivsPersonaByCodPer2 = tiivsPersonaByCodPer2;
		this.tiivsPersonaByCodPer1 = tiivsPersonaByCodPer1;
		this.codMultPer1 = codMultPer1;
		this.codMultPer2 = codMultPer2;
		this.estado = estado;
		this.fechaRevocatoria = fechaRevocatoria;
		this.codAgrup = codAgrup;
	}

	public int getCodRevocado() {
		return this.codRevocado;
	}

	public void setCodRevocado(int codRevocado) {
		this.codRevocado = codRevocado;
	}

	public TiivsPersona getTiivsPersonaByCodPer2() {
		return this.tiivsPersonaByCodPer2;
	}

	public void setTiivsPersonaByCodPer2(TiivsPersona tiivsPersonaByCodPer2) {
		this.tiivsPersonaByCodPer2 = tiivsPersonaByCodPer2;
	}

	public TiivsPersona getTiivsPersonaByCodPer1() {
		return this.tiivsPersonaByCodPer1;
	}

	public void setTiivsPersonaByCodPer1(TiivsPersona tiivsPersonaByCodPer1) {
		this.tiivsPersonaByCodPer1 = tiivsPersonaByCodPer1;
	}

	public String getCodMultPer1() {
		return this.codMultPer1;
	}

	public void setCodMultPer1(String codMultPer1) {
		this.codMultPer1 = codMultPer1;
	}

	public String getCodMultPer2() {
		return this.codMultPer2;
	}

	public void setCodMultPer2(String codMultPer2) {
		this.codMultPer2 = codMultPer2;
	}

	public Character getEstado() {
		return this.estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}

	public Date getFechaRevocatoria() {
		return this.fechaRevocatoria;
	}

	public void setFechaRevocatoria(Date fechaRevocatoria) {
		this.fechaRevocatoria = fechaRevocatoria;
	}

	public Integer getCodAgrup() {
		return this.codAgrup;
	}

	public void setCodAgrup(Integer codAgrup) {
		this.codAgrup = codAgrup;
	}

}
