package com.hildebrando.visado.modelo;

// Generated 11/01/2013 11:19:20 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TiivsOficina1 generated by hbm2java
 */
public class TiivsOficina1 implements java.io.Serializable {

	private String codOfi;
	private TiivsTerritorio tiivsTerritorio;
	private String desOfi;
	private Character activo;
	private Set<TiivsSolicitud> tiivsSolicituds = new HashSet<TiivsSolicitud>();

	public TiivsOficina1() {
	}

	public TiivsOficina1(String codOfi) {
		this.codOfi = codOfi;
	}

	public TiivsOficina1(String codOfi, TiivsTerritorio tiivsTerritorio,
			String desOfi, Character activo, Set tiivsSolicituds) {
		this.codOfi = codOfi;
		this.tiivsTerritorio = tiivsTerritorio;
		this.desOfi = desOfi;
		this.activo = activo;
		this.tiivsSolicituds = tiivsSolicituds;
	}

	public String getCodOfi() {
		return this.codOfi;
	}

	public void setCodOfi(String codOfi) {
		this.codOfi = codOfi;
	}

	public TiivsTerritorio getTiivsTerritorio() {
		return this.tiivsTerritorio;
	}

	public void setTiivsTerritorio(TiivsTerritorio tiivsTerritorio) {
		this.tiivsTerritorio = tiivsTerritorio;
	}

	public String getDesOfi() {
		return this.desOfi;
	}

	public void setDesOfi(String desOfi) {
		this.desOfi = desOfi;
	}

	public Character getActivo() {
		return this.activo;
	}

	public void setActivo(Character activo) {
		this.activo = activo;
	}

	public Set getTiivsSolicituds() {
		return this.tiivsSolicituds;
	}

	public void setTiivsSolicituds(Set tiivsSolicituds) {
		this.tiivsSolicituds = tiivsSolicituds;
	}

}
