package com.hildebrando.visado.modelo;

// Generated 05/12/2012 11:17:13 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TiivsGrupo generated by hbm2java
 */
public class TiivsGrupo implements java.io.Serializable {

	private String codGrupo;
	private String desGrupo;
	private Set tiivsTareas = new HashSet(0);
	private Set tiivsMiembros = new HashSet(0);

	public TiivsGrupo() {
	}

	public TiivsGrupo(String codGrupo, String desGrupo) {
		this.codGrupo = codGrupo;
		this.desGrupo = desGrupo;
	}

	public TiivsGrupo(String codGrupo, String desGrupo, Set tiivsTareas,
			Set tiivsMiembros) {
		this.codGrupo = codGrupo;
		this.desGrupo = desGrupo;
		this.tiivsTareas = tiivsTareas;
		this.tiivsMiembros = tiivsMiembros;
	}

	public String getCodGrupo() {
		return this.codGrupo;
	}

	public void setCodGrupo(String codGrupo) {
		this.codGrupo = codGrupo;
	}

	public String getDesGrupo() {
		return this.desGrupo;
	}

	public void setDesGrupo(String desGrupo) {
		this.desGrupo = desGrupo;
	}

	public Set getTiivsTareas() {
		return this.tiivsTareas;
	}

	public void setTiivsTareas(Set tiivsTareas) {
		this.tiivsTareas = tiivsTareas;
	}

	public Set getTiivsMiembros() {
		return this.tiivsMiembros;
	}

	public void setTiivsMiembros(Set tiivsMiembros) {
		this.tiivsMiembros = tiivsMiembros;
	}

}
