package com.hildebrando.visado.modelo;

// Generated 07/11/2012 02:39:40 PM by Hibernate Tools 3.4.0.CR1

/**
 * TiivsNivel generated by hbm2java
 */
public class TiivsNivel implements java.io.Serializable {

	private String codNiv;
	private String desNiv;
	private String estado;

	public TiivsNivel() {
	}

	public TiivsNivel(String codNiv) {
		this.codNiv = codNiv;
	}

	public TiivsNivel(String codNiv, String desNiv, String estado) {
		this.codNiv = codNiv;
		this.desNiv = desNiv;
		this.estado = estado;
	}

	public String getCodNiv() {
		return this.codNiv;
	}

	public void setCodNiv(String codNiv) {
		this.codNiv = codNiv;
	}

	public String getDesNiv() {
		return this.desNiv;
	}

	public void setDesNiv(String desNiv) {
		this.desNiv = desNiv;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

}
