package com.hildebrando.visado.modelo;

// Generated 12/12/2012 12:08:20 PM by Hibernate Tools 3.4.0.CR1

/**
 * TiivsNivel generated by hbm2java
 */
public class TiivsNivel implements java.io.Serializable {

	private TiivsNivelId id;

	public TiivsNivel() {
	}

	public TiivsNivel(TiivsNivelId id) {
		this.id = id;
	}

	public TiivsNivelId getId() {
		return this.id;
	}

	public void setId(TiivsNivelId id) {
		this.id = id;
	}

}
